{
    "60": "Square Shape \"Square-Shaped Fake-Out Art\"",
    "62": "Square Shape \"Square Creature Fake Out\"",
    "64": "Circular Shape \"Exceeded Circle Sculpting Art\"",
    "66": "Circular Shape \"Too-Much-Circle Creature\"",
    "68": "\"Lillies-Shaped Sculpting Art\"",
    "70": "\"Murderous Lilly Creatures\"", 
    "72": "Haniwa \"Not-this-Idol Sculpting Art\"",
    "74": "Haniwa \"Not-this-Idol Creature\"",
    "76": "\"Anarchy-Shaped Sculpting Art\"",
    "80": "\"GeomeTHICC Creature\"",
    "84": "\"Idola Dominance\"",
    "91": "Agile Skill \"Reverse Thrilling Shot\"",
    "92": "Agile Skill \"Lightning Neigh Like a Heron\"",
    "93": "Secret Ceremony \"Kurokomah Dukkha\"",
    "94": "\"Overflowing Epidemicity\"",
    "95": "Agile Skill \"Beyblade of Death\"",
    "96": "Agile Skill \"Black Pegasus Rear Shot\"",
    "97": "Agile Skill \"Washing Muscle Explosion\"",
    "98": "\"Peerless Dark Pegasus\"",
    "99": "\"Vengeful Cannibal Oni-Shaped Hoi Polloi\"",
    "100": "\"Deadly Deeds of Devilish Beasts\""
}