{
    "0": "Piercing Chill \"Ultimate Blizzard\"",
    "2": "Water \"Tail Fin Slap\"",
    "6": "Water \"Scale Wave\"",
    "8": "Water \"Raging Waves of the Reversed Scale\"",
    "9": "Water \"Great Raging Waves of the Reversed Scale\"",
    "10": "Dusk \"Flying Dusk\"",
    "14": "Dusk \"Eye Dusk\"",
    "16": "Dusk \"Blind Dusk\"",
    "18": "Dusk \"Multiplicative Dusk\"",
    "20": "Dusk \"Seventh Dusk\"",
    "21": "Dusk \"Ninth Dusk\"",
    "22": "Dusk \"Sinister Piercing Dusk\"",
    "26": "Berserk \"Moonlit Canine Teeth\"",
    "28": "Berserk \"Triangle Fang\"",
    "30": "Berserk \"Star Fang\"",
    "32": "Berserk \"Strange Roar\"",
    "34": "Berserk \"Full Moon Howling\"",
    "36": "Berserk \"Star Ring Pounce\"",
    "38": "Berserk \"High-Speed Pounce\"",
    "40": "Snatch \"Sounds of Jetavana's Bell\"",
    "44": "Shadow \"Demon Tower\"",
    "46": "Shadow \"Demon Tide\"",
    "48": "Snatch \"Wicked Musical Score\"",
    "50": "Snatch \"Malicious Musical Score\"",
    "51": "Snatch \"Double Score\"",
    "52": "Snatch \"Sounds of Anicca's Koto\"",
    "56": "Snatch \"Heian's Reverberation\"",
    "58": "Snatch \"Echo Chamber\"",
    "60": "Snatch \"Social Upheaval Koto Music Complement\"",
    "62": "Snatch \"Social Upheaval Requiem\"",
    "64": "Deceit Sign \"Reverse Needle Attack\"",
    "68": "Filop \"Danmaku Through the Looking-Glass\"",
    "70": "Filop \"Evil in the Mirror\"",
    "72": "Filop \"This Side Down\"",
    "74": "Filop \"Overturning All Under Heaven\"",
    "76": "Reverse Bow \"Dream Bow of Heaven & Earth\"",
    "78": "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
    "80": "Turnabout \"Reverse Hierarchy\"",
    "82": "Turnabout \"Change Air Brave\"",
    "84": "Small Beginning \"All Worlds Begin in Darkness\"",
    "86": "Small Beginning \"All Worlds End in Darkness\"",
    "88": "Big Beginning \"Resizing X-Blade -Bullets Lv.1-\"",
    "89": "Big Beginning \"Resizing X-Blade -Bullets Lv.2-\"",
    "90": "Big Beginning \"Resizing X-Blade -Bullets Lv.3-\"",
    "91": "Big Beginning \"Resizing X-Blade -Bullets Lv.MAX-\"",
    "92": "X-Blade \"Sparking War\"",
    "96": "Chaos and Destruction \"Resizing X-Blade -Target Lv.1-\"",
    "97": "Chaos and Destruction \"Resizing X-Blade -Target Lv.2-\"",
    "98": "Chaos and Destruction \"Resizing X-Blade -Target Lv.3-\"",
    "99": "Chaos and Destruction \"Resizing X-Blade -Target Lv.MAX-\"",
    "100": "\"X-Blade Shockwave\"",
    "102": "\"X-Blade Dense Shockwave\"",
    "104": "\"Kingdom Hearts's Seven Shining Lights\"",
    "106": "\"Kingdom Hearts's Seven Strong Lights\"",
    "108": "Snatch \"Storm Ensemble\"",
    "109": "Snatch \"Joururi World\"",
    "110": "First Darkness \"Planet Drop and Buster\"",
    "111": "Second Darkness \"Shadow Buster\"",
    "112": "Third Darkness \"Dark Three Strikes\"",
    "113": "Fourth Darkness \"Dark Quake\"",
    "114": "Fifth Darkness \"Dark Curvy Laser\"",
    "115": "Sixth Darkness \"Dark Rush\"",
    "116": "Seventh Darkness \"Dark Galaxy Rush\"",
    "117": "Eighth Darkness \"Dark Matter\"",
    "118": "\"Dark Galaxy\"",
    "119": "\"Chaos Beat\""
}