{
    "0": "Frozen Water \"Water Blizzard\"",
    "2": "Water \"Water Wave\"",
    "6": "Water \"Water Slide\"",
    "8": "Water \"Raging Waves of the Reversed Sitar\"",
    "9": "Water \"Great Raging Waves of the Reversed Sitar\"",
    "10": "Dusk \"Flying Dusk\"",
    "14": "Dusk \"Closed Dusk\"",
    "16": "Dusk \"Blind Dusk\"",
    "18": "Dusk \"Multiplicative Dusk\"",
    "20": "Dusk \"Seventh Dusk\"",
    "21": "Dusk \"Ninth Dusk\"",
    "22": "Dusk \"Sinister Piercing Dusk\"",
    "26": "Berserk \"Moonlit Racing Shockwave\"",
    "28": "Berserk \"Triangle Rush\"",
    "30": "Berserk \"Star Rush\"",
    "32": "Berserk \"Strange Circle Reject\"",
    "34": "Berserk \"Full Moon Circle Reject\"",
    "36": "Berserk \"Star Ring Dive\"",
    "38": "Berserk \"High-Speed Dive\"",
    "40": "Benben Tsukumo \"Sounds of Jetavana's Bell\"",
    "44": "Shadow \"Demon Tower\"",
    "46": "Shadow \"Demon Tide\"",
    "48": "Claw \"Wicked Musical Claw\"",
    "50": "Claw \"Malicious Musical Claw\"",
    "51": "Claws \"Double Claw\"",
    "52": "Yatsuhashi Tsukumo \"Sounds of Anicca's Koto\"",
    "56": "Music \"Music Reflect\"",
    "58": "Music \"Music Reflera\"",
    "59": "Music \"Music Reflega\"",
    "60": "Music Reversal \"Music Rising Just Behind You\"",
    "62": "Music Reversal \"Chaotic Music Rising Just Behind You\"",
    "64": "Deceit Sign \"Reverse Needle Attack\"",
    "68": "Reverse Sign \"Danmaku Through the Looking-Glass\"",
    "70": "Reverse Sign \"Evil in the Mirror\"",
    "72": "Reverse Sign \"This Side Down\"",
    "74": "Reverse Sign \"Overturning All Under Heaven\"",
    "76": "Reverse Bow \"Dream Bow of Heaven & Earth\"",
    "78": "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
    "80": "Turnabout \"Reverse Hierarchy\"",
    "82": "Turnabout \"Change Air Brave\"",
    "84": "Small Beginning \"First Shockwaves\"",
    "86": "Small Beginning \"First Rough Shockwaves\"",
    "88": "Light & Darkness \"Resizing X-Blade -Bullets Lv.1-\"",
    "89": "Light & Darkness \"Resizing X-Blade -Bullets Lv.2-\"",
    "90": "Light & Darkness \"Resizing X-Blade -Bullets Lv.3-\"",
    "91": "Light & Darkness \"Resizing X-Blade -Bullets Lv.MAX-\"",
    "92": "X-Blade \"Sparking War\"",
    "96": "Big End \"Resizing X-Blade -Target Lv.1-\"",
    "97": "Big End \"Resizing X-Blade -Target Lv.2-\"",
    "98": "Big End \"Resizing X-Blade -Target Lv.3-\"",
    "99": "Big End \"Resizing X-Blade -Target Lv.MAX-\"",
    "100": "\"X-Blade Shockwave\"",
    "102": "\"X-Blade Dense Shockwave\"",
    "104": "\"Kingdom Hearts's Seven Shining Lights\"",
    "106": "\"Kingdom Hearts's Seven Overly Shining Lights\"",
    "108": "Conjuring \"Eternal Musical Meek\"",
    "109": "Reflect \"One Reflects the Music\"",
    "110": "First Darkness \"Planet Drop and Buster\"",
    "111": "Second Darkness \"Shadow Buster\"",
    "112": "Third Darkness \"Dark Three Strikes\"",
    "113": "Fourth Darkness \"Dark Quake\"",
    "114": "Fifth Darkness \"Dark Curvy Laser\"",
    "115": "Sixth Darkness \"Dark Rush\"",
    "116": "Seventh Darkness \"Dark Galaxy Rush\"",
    "117": "Eighth Darkness \"Dark Matter\"",
    "118": "\"Dark Galaxy\"",
    "119": "\"Chaos Beat\""
}
