{
    "138": "Dance Sign \"Spin the Bamboo Stick\"",
    "140": "Mad Dance \"Lively Rave in the Dark City\"",
    "143": "Dance Sign \"Spin the Myoga-Ginger\"",
    "145": "Mad Dance \"Mind-Blowing Rave in the Dark City\"",
    "70": "Star Sign \"Beginning Light in the Back\"",
    "71": "Star Sign \"Standard Light in the Back\"",
    "72": "Star Sign \"Proud Light in the Back\"",
    "73": "Star Sign \"Critical Light in the Back\"",
    "74": "Summer Sunlight \"Bright Star Illuminating Nature\"",
    "76": "Summer Sunlight \"Sunshine of Abnormal Nature Madness\"",
    "78": "Fall Plenty \"Life Force Harvester\"",
    "80": "Fall Plenty \"Bumper Crop of Abnormally Extended Life\"",
    "82": "Winter Silence \"Dark Silent Snow Flower\"",
    "84": "Winter Silence \"Shadow in the Abnormally Cold Flower\"",
    "86": "Spring Link \"Spring Evening Blossom Shower\"",
    "88": "Spring Link \"Endless Evening Netherworld Butterflies\"",
    "133": "Time Hindrance \"Rewind of the Wet & Dry Seasons\"",
    "90": "Stolen Release \"Breezy Cherry Blossom\"",
    "94": "Stolen Release \"Perfect Summer Ice\"",
    "98": "Stolen Release \"Crazy Fall Wind\"",
    "102": "Stolen Release \"Extreme Winter\"",
    "106": "Drum Dance \"Tremendous Cheers\"",
    "107": "Mad Dance \"Lunatic Backup Dance\"",
    "108": "Bullet Dance \"Twin Cyclones\"",
    "109": "Magic Link \"Mirrored Dark Milky Way\"",
    "110": "Celestial Link \"The Doyou Stones Reaching the Heavens\"",
    "111": "Miracle Link \"Thaumaturgy of the Native Gods\"",
    "112": "Reverse Link \"Mirage Bow of the Reversed Arrow Rain\"",
    "113": "Spirit Link \"Fantasy Seal -Homing Amulet-\"",
    "114": "Illusion Link \"Four Directions Remote Mesmerism (Origin Remote)\"",
    "115": "Star Link \"Shining Seven Sapphires\"",
    "116": "Sun&Moon Link \"Reckless Flare VS. Hourai Danmaku\"",
    "117": "Three Servants \"Mirage Split of Mental and Life Forces\"",
    "118": "Secret God \"Lingering Four Seasons\"",
    "137": "\"The True Face of Everyone's Nobody\""
}