{
    "38": "Cute Meme Sign \"Buwwet Golwem\"",
    "40": "Cute Meme Sign \"Gigwantic Pwet Buwwet Lifefowm\"",
    "70": "Hidden Starlight \"Beginning Light in the Back\"",
    "71": "Hidden Starlight \"Standard Light in the Back\"",
    "72": "Hidden Starlight \"Proud Light in the Back\"",
    "73": "Hidden Starlight \"Critical Light in the Back\"",
    "74": "Summer Remembrance \"Taste the Sunlight, Nature\"",
    "76": "Summer Remembrance \"Sunshine of Abnormal Nature Madness\"",
    "78": "Fall Remembrance \"Life Force Harvester\"",
    "80": "Fall Remembrance \"Lively Abnormal Bumper Crop\"",
    "82": "Winter Remembrance \"Dark Snow Flower\"",
    "84": "Winter Remembrance \"Shadow in the Abnormally Cold Flower\"",
    "86": "Spring Remembrance \"Spring Evening Blossom Shower\"",
    "88": "Spring Remembrance \"Endless Evening Netherworld Butterflies\"",
    "133": "Hidden Wet&Dry Seasons \"From Thunderstorm to Heat Wave\"",
    "90": "Stolen Release \"Breezy Cherry Blossom\"",
    "94": "Stolen Release \"Perfect Summer Ice\"",
    "98": "Stolen Release \"Crazy Fall Wind\"",
    "102": "Stolen Release \"Extreme Winter\"",
    "106": "Drum Dance \"Tremendous Cheers\"",
    "107": "Mad Dance \"Lunatic Backup Dance\"",
    "108": "Bullet Dance \"Twin Hurricanes\"",
    "109": "Secret Magic \"Omnidirectional Dark Milky Way\"",
    "110": "Secret Heaven&Earth \"The Earth's Power Reaching the Heavens\"",
    "111": "Secret Miracle \"Thaumaturgy of the Native Gods\"",
    "112": "Secret Reverse \"Mirage Bow of the Reversed Arrow Rain\"",
    "113": "Secret Spirit \"Homing Amulet Barrage\"",
    "114": "Secret Illusion \"Four Directions Remote Mesmerism (Origin Remote)\"",
    "115": "Secret Stars \"Shining Seven Sapphires\"",
    "116": "Secret Sun&Moon Clash \"Reckless Stars VS. Lunatic Danmaku\"",
    "117": "Reality Shift \"Mirage Split Back Sword\"",
    "118": "\"Hidden God of the Four Seasons\"",
    "137": "\"A Nobody's Identity Crisis\""
}