{
    "70": "Light in the Back \"Easygoing Hidden Stars of a Secret Human\"",
    "71": "Light in the Back \"Hidden Stars of a Secret Human\"",
    "72": "Light in the Back \"Hard Hidden Stars of a Secret Human\"",
    "73": "Light in the Back \"Lunatic Stars of an Absolutely Secret Human\"",
    "74": "Hidden Summer \"Taste the Sunlight\"",
    "76": "Hidden Summer \"Zenith Sunshine of Abnormal Agressivity\"",
    "78": "Hidden Fall \"Bumper Crop Turnabout\"",
    "80": "Hidden Fall \"Reversal of the Abnormal Bumper Crop\"",
    "82": "Hidden Winter \"Dark Snow Cloak\"",
    "84": "Hidden Winter \"Nightmarish Abnormal Snow Ball Blizzard\"",
    "86": "Hidden Spring \"Spring Evening Blossom Shower\"",
    "88": "Hidden Spring \"Endless Evening Abnormal Blossom Butterflies\"",
    "131": "Hidden Wet&Dry Seasons \"From Thunderstorm to Heat Wave\"",
    "90": "Hidden Snatch \"Hidden Breezy Cherry Blossom\"",
    "94": "Hidden Snatch \"Hidden Perfect Summer Ice\"",
    "98": "Hidden Snatch \"Hidden Crazy Fall Wind\"",
    "102": "Hidden Snatch \"Hidden Extreme Winter\"",
    "109": "Secret Love \"Light Stars in Darkness\"",
    "110": "Secret Earth \"Rock Burst from the Earth's Power\"",
    "111": "Native Secrecy \"Double Snake and the Crawling Frogs\"",
    "112": "Reversed Secret \"Reversal Bow of Back & Forth\"",
    "113": "Secret Barrier \"Pseudo-Homing Amulet Barrage\"",
    "114": "Lunatic Illusion \"Returning Back Shots Cross (Perpendicular Cross)\"",
    "115": "Secret Stars \"Shining Seven Sapphires\"",
    "116": "Secret Enemies \"Recklessly Vengeful Stars VS. Lunatic Danmaku\"",
    "117": "Reality Shift \"Mirage Split Back Sword\"",
    "118": "\"The Secret Human who Never Was\""
}