{
    "78": "\"Pure Light of the HOLYSHITTHATSFAST\"",
    "82": "\"Legacy of Lunatic Kingdom's Downfall\"",
    "86": "\"Sweeping Divine Speen World\"",
    "88": "\"Masochist's Divine Speen World\"",
    "90": "\"TSS Goes Behind You, Hee~\"",
    "94": "\"Oh If Only You Could Teleport\"",
    "98": "\"Overflowing Point Item Value\"",
    "101": "\"Overflowing Point Item Value\"",
    "102": "Junk Sign \"Unpurely Junkery Hell\"",
    "104": "Junk Sign \"A Pristine Junkery Hell\"",
    "109": "Otherworld \"Walltastic Ōmagatoki\"",
    "110": "Earth \"You're Waaaay too Impure\"",
    "111": "Moon \"Apollo Polished Shining Reflection Mirror\"",
    "112": "\"You're Not Getting Away Ma Boi\"",
    "113": "Otherworld \"Hell's Too-Crazy-For-You Danmaku\"",
    "114": "Earth \"Literal Rain Falling in Hell\"",
    "115": "Moon \"Lunatic Cannon\"",
    "116": "\"Pristine Danmaku for WAITWHATTHE-\"",
    "117": "\"Heartless Trinitarian Rhapsody\"",
    "118": "\"First and Last Pristine Danmaku Hell\""
}