{
    "0": "Bug Sign \"Icicle Blizzard\"",
    "2": "Bug Sign \"Melted Icicle Blizzard\"",
    "4": "Bug Freeze \"Fluttering Cool Summer\"",
    "6": "Bug Freeze \"Midsummer Ice Wingbeats\"",
    "8": "Rain Sign \"Feather Dance\"",
    "10": "Rain Sign \"Feather Mad Dance\"",
    "12": "Wind Sign \"Wing Grind\"",
    "14": "Wind Sign \"Steel Wing Grind\"",
    "16": "Tornado \"Blade Gust\"",
    "18": "Tornado \"Bloody Blade Gust\"",
    "20": "\"Pure Spring That Never Was\"",
    "22": "Reality Sign \"Non-Fantasy Seal -Concentrate-\"",
    "24": "Reality Sign \"Non-Fantasy Seal -Marred-\"",
    "26": "\"Persuasion Curvy Needles\"",
    "29": "\"Nine Persuasion Curvy Needles\"",
    "30": "Illusionary Double \"Double Cherry Blossom Seal\"",
    "34": "Orb Sign \"Light Burst\"",
    "36": "Orb Sign \"Light Burst\"",
    "38": "Magic Bullet \"Test Slave\"",
    "42": "Light Sign \"Flames Reaching the Moon\"",
    "46": "Darkness Sign \"Dark Thunder\"",
    "48": "Darkness Sign \"Dark Thundara\"",
    "49": "Darkness Sign \"Dark Thundaga\"",
    "50": "Light Sign \"Ragnarok\"",
    "54": "Darkness Sign \"Chaos Stars\"",
    "62": "Light & Darkness Sign \"Chaos Reversal\"",
    "58": "Reverse Light \"Behind Reversal\"",
    "66": "Light & Darkness Sign \"Dark Ragnarok\"",
    "118": "Okina Matara \"Anarchy Bullet Hell\"",
    "109": "Reverse Secrecy \"Reverse Darkness\"",
    "115": "Darkness Sign \"Inverse Halo\"",
    "106": "Light & Darkness Sign \"Falling Back Storm\"",
    "107": "Light & Darkness Sign \"Rising Back Storm\"",
    "108": "Light & Darkness Sign \"Union of the Two Halves\"",
    "74": "Summer Memories \"Scorch from the Bright Star\"",
    "78": "Fall Memories \"Reverse Miracle\"",
    "82": "Winter Memories \"Solo Dark Blizzard Limit\"",
    "86": "Spring Memories \"Reverse Cherry Blossom Attack\"",
    "87": "Spring Memories \"Reverse Cherry Blossom Attack\"",
    "90": "Okina Matara \"Hidden Breezy Cherry Blossom\"",
    "94": "Okina Matara \"Hidden Perfect Summer Ice\"",
    "98": "Okina Matara \"Hidden Crazy Fall Wind\"",
    "102": "Okina Matara \"Hidden Extreme Winter\"",
    "113": "Reversal \"Dark Spiral\"",
    "114": "Reversal \"Reverse Spiral Attack\"",
    "116": "Reversal \"Falling Enemies\"",
    "111": "Bind \"Danmaku Catcher\"",
    "37": "Orb Sign \"Light Burst Combo\"",
    "44": "Light Blast \"Flames Reaching the Moon at Winter\"",
    "117": "\"The Phantom Secretly Existing on Your Back\"",
    "70": "Miracle Memories \"Memory of the Bright Hidden Stars\"",
    "73": "Miracle Memories \"Memory of the Overly Bright Hidden Stars\"",
    "84": "Winter Memories \"Solo Dark Blizzara Limit\"",
    "85": "Winter Memories \"Solo Dark Blizzaga Limit\"",
    "76": "Summer Memories \"Scorching Drought from the Bright Star\"",
    "80": "Fall Memories \"Change Air Miracle\"",
    "88": "Spring Memories \"Reverse Abnormal Cherry Blossom Attack\"",
    "89": "Spring Memories \"Reverse Abnormal Cherry Blossom Attack\"",
    "40": "Magic Bullet \"Gigantic Test Slave\"",
    "68": "Light & Darkness Sign \"Darkest Ragnarok\"",
    "110": "Deceit Secrecy \"Shot in the Back\"",
    "112": "Reverse Secrecy \"Overturning All Behind You\""
}
