{
    "0": "Weed Sign \"Falling Weeds of Stoners\"",
    "2": "Stoner Sign \"Stoner Sky\"",
    "4": "Stoner Sign \"The Smoke Sky and a Stoner's Heart\"",
    "6": "Plenty Sign \"Marijuana Harvester\"",
    "8": "Bumper Crop \"Promise of the Weed God\"",
    "10": "Bad Luck Sign \"Bad Stoner\"",
    "12": "Bad Luck Sign \"Biorhythm of the Misfortune Joint\"",
    "14": "Flawed Sign \"Broken Joint\"",
    "16": "Scar \"Broken Joint of Highness\"",
    "18": "Evil Spirit \"Stoner's Wheel\"",
    "20": "Fate \"Old Lady Ohgane's Crack\"",
    "22": "Wound Sign \"Smoke Flow\"",
    "24": "Wound Sign \"Exiled Dealer\"",
    "26": "Optics \"Visibility on Crack\"",
    "28": "Optics \"Stoner's Visibility\"",
    "30": "Flood \"Creeping Smoke\"",
    "32": "Flood \"Dense Crack\"",
    "33": "High \"Heavily Lightened Joint\"",
    "34": "Fire Sign \"Kappa's Joint\"",
    "36": "Fire Sign \"Kappa's Fire Crumbles\"",
    "37": "Fire Sign \"Drop It Like It's Hot\"",
    "38": "Kappa \"Monster Joint\"",
    "40": "Kappa \"Exteeeending Stoneeeeer\"",
    "41": "Kappa \"Spin the Marijuana Ring\"",
    "42": "Crossroad Sign \"High on Heaven\"",
    "44": "Crossroad Sign \"Marijuana Cross\"",
    "46": "Weed God \"Weed God's Weed-Veiling\"",
    "48": "Weed God \"Tengu's Smoke Wall\"",
    "49": "Weed God \"Sensual Seduction\"",
    "50": "\"Like a Cheetah on Coke\"",
    "51": "\"Like a Cheetah on Coke\"",
    "52": "\"Peerless Smoke the Weed\"",
    "53": "Blockade Sign \"Marijuana God's Procession\"",
    "55": "Blockade Sign \"Advent of the Divine Stoner\"",
    "56": "Blockade Sign \"Beautiful Herb Shining Through Heaven and Earth\"",
    "57": "Esoterica \"Gray Stoner Experiment\"",
    "59": "Esoterica \"Forgotten Herb\"",
    "60": "Esoterica \"Secretly Inherited Art of French Inhale\"",
    "61": "Miracle \"Daytime Weed Stars\"",
    "63": "Miracle \"Night with Bright Weed Stars\"",
    "64": "Miracle \"Night with Overly Bright Weed Stars\"",
    "65": "Herb Cutting \"The Day the Herb Split\"",
    "67": "Herb Cutting \"Snoop Dog's Miracle\"",
    "68": "Herb Cutting \"Snoop Dog's Miracle\"",
    "69": "Preparation \"Crack Creation to Call the Godly Smoke\"",
    "71": "Preparation \"Summon Vato\"",
    "73": "Miracle \"God's Weed\"",
    "75": "Great Miracle \"Marijuana's Divine Smoke\"",
    "77": "Divine Festival \"Expanded Joint\"",
    "79": "Weird Festival \"Snoop Dog's Boisterous Dance\"",
    "80": "Weird Festival \"Snoop Dog's Boisterous Dance\"",
    "81": "Joint \"God's Joint Creation\"",
    "83": "Forgotten Ash \"Unremembered Smoking\"",
    "84": "Divine Herb \"Stoner's Herb Size Mistake\"",
    "85": "Crop Sign \"Powder Crop\"",
    "87": "Mystery \"Clear Smoke\"",
    "88": "Mystery \"Stoner's Double Vision\"",
    "89": "Heaven's Smoke \"Falling Joint Ashes\"",
    "91": "Heaven's Dragon \"That Good\"",
    "93": "\"Mountain of Stoners\"",
    "95": "\"Divine Virtues of Weed Smoking\"",
    "97": "God Sign \"Beautiful Spring like This Crack\"",
    "98": "God Sign \"Ancient Fate Linked by Ashes\"",
    "99": "God Sign \"Joint Trail\"",
    "100": "Snoop Dog's Dance \"Two Bows, Two Claps, and One Bow\"",
    "101": "Native God \"Lord Long-Joint Powders\"",
    "102": "Divine Tool \"Moriya's Stoner Rings\"",
    "103": "Joint Sign \"Inside of a Crack of Horrid Stench\"",
    "104": "Tutorial \"How To Basic Crops The Weed\"",
    "105": "Native God \"Seven Stoners and That Tree\"",
    "106": "Native God \"FroggyOG Braves the Weed Remains\"",
    "107": "Native God \"Frogs On Crack\"",
    "108": "\"Stoner War ~ 'Sweat' Snoop Dogg vs David Guetta\"",
    "109": "Stoner Sign \"Marijuana-sama\""
}