{
    "0": "Forgotten Challenge \"Homing Gale of Severance\"",
    "2": "Forgotten Challenge \"Homing Gale of Severance - Cherry Blossoms -\"",
    "4": "Forgotten Challenge \"Small Whirlwind to the Void\"",
    "6": "Forgotten Challenge \"Small Whirlwind to the Void - Cherry Blossoms -\"",
    "8": "Forgotten Challenge \"Disappearance in Cherry Blossom\"",
    "12": "Book Aura \"Saigyou Cherry Blossom Blizzard Snatch\"",
    "14": "Remembrance \"Remembrance Echo\"",
    "16": "Remembrance \"Remembrance Echo Scramble\"",
    "18": "Remembrance \"Power Remembrance\"",
    "22": "Remembrance \"Long-Range Echo\"",
    "24": "Remembrance \"Amplify Echo\"",
    "26": "Remembrance \"Bullet Magnet\"",
    "28": "Remembrance \"Bullet Magnera\"",
    "29": "Remembrance \"Bullet Magnega\"",
    "30": "Rainbow Sign \"Umbrella Cyclone\"",
    "32": "Recovery \"Shadow Cure\"",
    "34": "Recovery \"Shadow Cura\"",
    "35": "Recovery \"Shadow Curaga\"",
    "36": "Poison Arrow \"Poison Raze\"",
    "38": "Poison Arrow \"Poison Murder\"",
    "40": "Darkness \"Dark Cure\"",
    "42": "Darkness \"Dark Cura\"",
    "43": "Darkness \"Dark Curaga\"",
    "44": "Darkness \"Dark Orb Blow\"",
    "45": "Darkness \"Darkest Orb Blow\"",
    "47": "Darkness \"Racing Team Shockwave\"",
    "51": "Darkness \"Lurking Guardian\"",
    "53": "Spirit Link \"Phantom Charge\"",
    "55": "Darkness \"Dark Soul\"",
    "59": "Thunder Arrow \"Die in a Cyclone\"",
    "60": "Thunder Arrow \"Die in a Cyclone\"",
    "61": "Thunder Arrow \"Die in a Tornado\"",
    "62": "Glider \"Grinding Glider\"",
    "64": "Glider \"Ascending Glider\"",
    "66": "Darkness \"Orb Buster\"",
    "70": "Blaze Sign \"Raging Wave\"",
    "72": "Blaze Sign \"Raging Storm\"",
    "74": "Darkness \"Invitation to Darkness\"",
    "78": "Light \"Faith\"",
    "80": "Light \"Salvation\"",
    "82": "Light \"The Light in One's Heart\"",
    "84": "Light \"The Strong Light in One's Heart\"",
    "86": "Corrupted Summon \"Possessed Demons\"",
    "90": "Rotating Particles \"Event Horizon\"",
    "93": "Rotating Particles \"Magic Hour\"",
    "94": "Light \"Halo of the Guse Kannon\"",
    "96": "Light \"Guse Flash\"",
    "98": "Light \"Shining Light within Darkness\"",
    "100": "Light \"Lingering Light within Darkness\"",
    "102": "Limit Break \"Falling Light within One's Heart\"",
    "104": "Final Limit \"Newborn Hope within Darkness\"",
    "106": "Nothingness \"Flying Random Swords\"",
    "107": "Nothingness \"Flying Arrows Combo\"",
    "108": "Absent Silhouette \"Aimed Despair\"",
    "109": "First Test \"Primate Danmaku Transformation\"",
    "110": "Second Test \"Carnivorous Danmaku Transformation\"",
    "111": "Third Test \"Avian Danmaku Transformation\"",
    "112": "Fourth Test \"Amphibian Danmaku Transformation\"",
    "113": "Fifth Test \"Scrolls of Frolicking Animals\"",
    "114": "Sixth Test \"Attack on Humans\"",
    "115": "Seventh Test \"Animal Swarm\"",
    "116": "Illusion \"A Shrine Maiden's Reflection\"",
    "117": "\"Transformation Rain\"",
    "118": "\"Final Test\"",
    "119": "Book Overdrive \"Cherry Blossom Blizzard Hell Snatch\"",
    "120": "Remembrance \"Deep Anxiety Confusion Echo\"",
    "121": "Poison Arrow \"Shadow Murderer\"",
    "122": "Special Attack \"Mega Destruction Dark Balls of Darkness and Destruction & Knuckles\"",
    "123": "Darkness \"Die in a Thunderstorm\"",
    "124": "Darkness \"Invitation to the Deepest Abyss\"",
    "125": "\"Heart Particle Storm\"",
    "126": "\"Overdrive Test\""
}
