{
    "0": "Forgotten Challenge \"Gale of Severance\"",
    "2": "Forgotten Challenge \"Gale of Severance - Cherry Blossoms -\"",
    "4": "Forgotten Challenge \"Small Whirlwind to the Void\"",
    "6": "Forgotten Challenge \"Small Whirlwind to the Void - Cherry Blossoms -\"",
    "8": "Sleep Sign \"Endless Nap under Breezy Cherry Blossoms\"",
    "12": "Limit \"Full Bloom\"",
    "14": "Magic \"Bullet Reflect\"",
    "16": "Magic \"Bullet Reflera\"",
    "17": "Magic \"Bullet Reflega\"",
    "18": "Magic \"Power Reflect\"",
    "20": "Magic \"Power Reflera\"",
    "21": "Magic \"Power Reflega\"",
    "22": "Magic \"Off Border Reflect\"",
    "24": "Magic \"Off Border Reflera\"",
    "25": "Magic \"Off Border Reflega\"",
    "26": "Magic \"Bullet Magnet\"",
    "28": "Magic \"Bullet Magnera\"",
    "29": "Magic \"Bullet Magnega\"",
    "30": "Expiring Light \"Prism Windmill\"",
    "32": "Recovery \"Shadow Cure\"",
    "34": "Recovery \"Shadow Cura\"",
    "35": "Recovery \"Shadow Curaga\"",
    "36": "Poison Arrow \"Shadow Raze\"",
    "38": "Poison Arrow \"Shadow Murder\"",
    "40": "Darkness Sign \"Dark Cure\"",
    "42": "Darkness Sign \"Dark Cura\"",
    "43": "Darkness Sign \"Dark Curaga\"",
    "44": "Darkness Sign \"Dark Orb Blow\"",
    "45": "Darkness Sign \"Darkest Orb Blow\"",
    "47": "Darkness Sign \"Racing Team Shockwave\"",
    "51": "Darkness Sign \"Lurking Guardian\"",
    "53": "Spirit Link \"Phantom Charge\"",
    "55": "Darkness Sign \"Dark Soul\"",
    "59": "Magic Sign \"Dark Thunder\"",
    "60": "Magic Sign \"Dark Thundara\"",
    "61": "Magic Sign \"Dark Thundaga\"",
    "62": "Glider \"Grinding Glider\"",
    "64": "Glider \"Ascending Glider\"",
    "66": "Darkness Sign \"Orb Buster\"",
    "70": "Fire Magic \"Raging Wave\"",
    "72": "Fire Magic \"Raging Storm\"",
    "74": "Darkness Sign \"Invitation to Darkness\"",
    "78": "Feeble Light \"Radiance from the Back\"",
    "80": "Feeble Light \"Light from the Back\"",
    "82": "Expiring Light \"The Clearing Haze\"",
    "84": "Expiring Light \"The Remaining Light\"",
    "86": "Corrupted Summon \"Possessed Demons\"",
    "90": "Rotating Particles \"Emerging Darkness\"",
    "93": "Rotating Particles \"Emerging Light Remnants\"",
    "94": "Light Sign \"Solo Limit\"",
    "96": "Light Sign \"Solo Limit\"",
    "98": "Secret God \"Hidden Light within Darkness\"",
    "100": "Secret God \"Hidden Eternal Light within Darkness\"",
    "102": "\"Falling Heart in Darkness\"",
    "104": "\"Crumbling Heart within Darkness\"",
    "106": "\"Firaga Burst\"",
    "107": "\"Teleport Arrows\"",
    "108": "\"Pure Redirection\"",
    "109": "First Test \"Fantasy Light -Concentrate-\"",
    "110": "Second Test \"Horizontal Fang\"",
    "111": "Third Test \"Vertical Fang\"",
    "112": "Fourth Test \"Seal Explosion\"",
    "113": "Fifth Test \"Chaotic Light\"",
    "114": "Sixth Test \"Light Wave\"",
    "115": "Seventh Test \"Blade Storm\"",
    "116": "Illusion \"A Shrine Maiden's Reflection\"",
    "117": "\"Penultimate Test Against Time\"",
    "118": "\"Final Test\"",
    "119": "Overdrive Limit \"Bloom Doom\"",
    "120": "Advanced Magic \"Off Border Refleja\"",
    "121": "Poison Arrow \"Shadow Murderer\"",
    "122": "Darkness Sign \"Darkest Storm\"",
    "123": "Advanced Magic \"Dark Thundaja\"",
    "124": "Darkness Sign \"Invitation to the Deepest Abyss\"",
    "125": "\"Heart Particle Storm\"",
    "126": "\"Overdrive Test\""
}
