{
    "0": "Item Finder \"Magnera\"",
    "1": "Item Finder \"Magnega\"",
    "2": "Lucky Lucky \"Rare Metal Detector\"",
    "4": "Lucky Lucky \"Gold Detector\"",
    "6": "Vision Sign \"Item-Finding Book\"",
    "8": "Vision Sign \"High Sensitivity Item Finding Book\"",
    "9": "Defense Sign \"Protecting Books\"",
    "10": "Large Ring \"Umbrella Halo\"",
    "12": "Large Ring \"Hello Forgotten World\"",
    "14": "Umbrella Sign \"Parasol Star Symphony\"",
    "16": "Umbrella Sign \"Parasol Star Memories\"",
    "18": "Rain Sign \"A Rainy Night's Ghost Story\"",
    "20": "Umbrella \"Super Water-Repelling Bone-Dry Monster\"",
    "22": "Monster Sign \"A Forgotten Umbrella's Night Train\"",
    "24": "Monster Train \"Spare Umbrella Express Night Carnival\"",
    "26": "Berserk \"An Unarguable Lunatic Impact\"",
    "28": "Berserk \"Hell Claymore Storm\"",
    "29": "Berserk \"Hell Lunatic Storm\"",
    "30": "Berserk \"Side Quake\"",
    "32": "Berserk \"Even More Side Quakes\"",
    "33": "Berserk \"Lunatic Side Quake\"",
    "34": "Berserk \"Lunatic Smash\"",
    "36": "Annihilation \"Lunatic Combo\"",
    "38": "Berserk \"Kingdom Hearts Beam\"",
    "40": "Berserk \"Scorching Kingdom Hearts Beam\"",
    "41": "Berserk \"Final Limit Berserk\"",
    "42": "Quake \"Dragging Lunatic\"",
    "44": "Quake \"Foundering Lunatic\"",
    "45": "Quake \"Sinking Lunatic\"",
    "46": "Minamitsu Murasa \"Deep Vortex\"",
    "48": "Minamitsu Murasa \"Sinkable Vortex\"",
    "50": "Berserk \"Limit Break\"",
    "52": "Berserk \"Claymore Storm\"",
    "53": "Berserk \"Eternal Lunatic Storm\"",
    "54": "Ghost Mushroom \"Dark Ghost\"",
    "55": "Ghost Mushroom \"Spirit Trance Attack\"",
    "56": "Ghost Mushroom \"Spirit Trance Attack\"",
    "57": "Light \"Holy Burst\"",
    "59": "Light \"Holy Burst\"",
    "60": "Light \"Holy Burst\"",
    "61": "Light \"Inverse Burst\"",
    "63": "Light \"Inverse Burst\"",
    "64": "Light \"Inverse Burst\"",
    "65": "Light \"Salvation\"",
    "67": "Light \"Faith\"",
    "69": "Ability \"Expanded Strike Raid\"",
    "70": "Ability \"Expanded Double Strike Raid\"",
    "71": "Ability \"Expanded Double Strike Raid\"",
    "72": "Ability \"Expanded Double Strike Raid\"",
    "73": "Limit Break \"Event Horizon\"",
    "75": "Limit Break \"Event Horizon\"",
    "76": "\"Magic Hour\"",
    "77": "Light \"Dream Mist\"",
    "79": "Light \"Dream Cloud\"",
    "80": "Darkness \"Nightmarish Cloud\"",
    "81": "Magic \"Grimoire Butterfly\"",
    "83": "Magic \"Dream Butterfly\"",
    "85": "Light Magic \"Circle Ragnarok\"",
    "87": "Light Magic \"Great Circle Ragnarok\"",
    "88": "Light Magic \"Great Circle Ragnarok\"",
    "89": "Remembrance \"Devil's Recitation\"",
    "91": "Remembrance \"Devil's Recitation\"",
    "92": "Remembrance \"Devil's Recitation\"",
    "94": "\"Sonic Book\"",
    "95": "Superhuman Flowmotion \"Nonamé\"",
    "96": "\"Sealed Nothingness\"",
    "98": "\"Eternally Sealed Nothingness\"",
    "99": "\"Eternally Sealed Nothingness\"",
    "100": "Umbrella Sign \"Lightly Falling Large Raindrops\"",
    "101": "Surprising Rain \"Guerrilla Typhoon\"",
    "102": "Halo \"Karakasa Surprising Flash\"",
    "103": "Darkness \"Light within Darkness\"",
    "104": "Supposed Hearts \"Red Dream Portals of Rage\"",
    "105": "Nothingness \"Green Bind\"",
    "106": "Supposed Hearts \"Blue Dream Portals of Grief\"",
    "107": "Illusion \"Danmaku Chimera\"",
    "108": "Supposed Hearts \"Green Dream Portals of Justice\"",
    "109": "Flying Swords \"Undefined Darkness\"",
    "110": "Supposed Hearts \"Rainbow Dream Portals of Terror\"",
    "111": "\"Interdiction\"",
    "112": "Final Limit \"All-Vanity\"",
    "93": "\"Sonic Dive\""
}
