{
    "0": "Back Sign \"First Halo\"",
    "1": "Back Sign \"First Halo\"",
    "2": "Back Sign \"Halo of the Secret Human\"",
    "4": "Back Sign \"Halo of the Absolute Secret Human\"",
    "6": "Circle Sign \"Circle Raid\"",
    "8": "Circle Sign \"Long-Range Circle Raid\"",
    "9": "Defense Sign \"Blizzard Shield\"",
    "10": "Large Ring \"Umbrella Halo\"",
    "12": "Large Ring \"Hello Forgotten World\"",
    "14": "Umbrella Sign \"Parasol Star Symphony\"",
    "16": "Umbrella Sign \"Parasol Star Memories\"",
    "18": "Rain Sign \"A Rainy Night's Ghost Story\"",
    "20": "Umbrella \"Super Water-Repelling Bone-Dry Monster\"",
    "22": "Monster Sign \"A Forgotten Umbrella's Night Train\"",
    "24": "Monster Train \"Spare Umbrella Express Night Carnival\"",
    "26": "Rock Slide \"Knocking Down Rock Slide\"",
    "28": "Rock Slide \"Hell Rock Storm\"",
    "29": "Rock Slide \"Hellish Falling Earth\"",
    "30": "Rock Slide \"Side Quake\"",
    "32": "Rock Slide \"Side Impact Quake\"",
    "33": "Rock Slide \"Wall Impact\"",
    "34": "Rock Smash \"Rockshatter\"",
    "36": "Annihilation \"Side Rock Slide\"",
    "38": "Rock Polish \"Rock Beam\"",
    "40": "Final Limit \"Ayers Rock\"",
    "41": "Final Limit \"Ayers Rock\"",
    "42": "Quake \"Lunatic Throw\"",
    "44": "Quake \"Lunatic Strike Raid\"",
    "45": "Quake \"Lunatic Sinkable Raid\"",
    "46": "Vortex \"Deep Furies\"",
    "48": "Vortex \"Sinkable Furies\"",
    "50": "Limit Break \"Berserk\"",
    "52": "Berserk \"Claymore Storm\"",
    "53": "Berserk \"Eternal Lunatic Storm\"",
    "54": "Dark Fading \"Dark Nobody\"",
    "55": "Dark Fading \"Nobody Trance\"",
    "56": "Dark Fading \"Nobody Trance\"",
    "57": "Light \"Omni Laser\"",
    "59": "Light \"Omni Laser\"",
    "60": "Light \"Omni Laser\"",
    "61": "Secret Halo \"Ultima Laser\"",
    "63": "Secret Halo \"Ultima Laser\"",
    "64": "Secret Halo \"Ultima Laser\"",
    "65": "Halo \"Light Tide\"",
    "67": "Secret Halo \"Secret Aura\"",
    "69": "Double Canon \"Expanded Strike Raid\"",
    "70": "Double Canon \"Expanded Double Strike Raid\"",
    "71": "Double Canon \"Expanded Double Strike Raid\"",
    "72": "Double Canon \"Expanded Double Strike Raid\"",
    "73": "Side Sign \"Hidden Radiance\"",
    "75": "Side Sign \"Hidden Radiance\"",
    "76": "\"Ultimate Absolute Hidden Light\"",
    "77": "Light \"Dream Mist\"",
    "79": "Light \"Dream Cloud\"",
    "80": "Darkness \"Nightmarish Cloud\"",
    "81": "Back Sign \"Butterfly of Nothingness\"",
    "83": "Back Sign \"Hidden Butterfly from the Back Door\"",
    "85": "Light Magic \"Circle Ragnarok\"",
    "87": "Light Magic \"Great Circle Ragnarok\"",
    "88": "Light Magic \"Great Circle Ragnarok\"",
    "89": "Secret God \"Hidden Devil in Four Lights\"",
    "91": "Secret God \"Hidden Devil in Four Lights\"",
    "92": "Secret God \"Hidden Devil in Four Lights\"",
    "94": "\"Dark Aura\"",
    "95": "\"Dark Aura\"",
    "96": "\"Sealed Nothingness\"",
    "98": "\"Eternally Sealed Nothingness\"",
    "99": "\"Eternally Sealed Nothingness\"",
    "100": "Umbrella Sign \"Lightly Falling Large Raindrops\"",
    "101": "Surprising Rain \"Guerrilla Typhoon\"",
    "102": "Halo \"Karakasa Surprising Flash\"",
    "103": "Darkness \"Light within Darkness\"",
    "104": "Assumed Hearts \"Red Dream Portals of Rage\"",
    "105": "Nothingness \"Green Bind\"",
    "106": "Assumed Hearts \"Blue Dream Portals of Grief\"",
    "107": "Illusion \"Mirage Laser\"",
    "108": "Assumed Hearts \"Green Dream Portals of Justice\"",
    "109": "Flying Swords \"Darkness of the Unknown\"",
    "110": "Assumed Hearts \"Rainbow Dream Portals of Terror\"",
    "111": "\"Interdiction\"",
    "112": "Final Limit \"All-Vanity\"",
    "93": "\"Dark Aura\""
}
