{
    "44": "Reprisal \"Payback Berserk Roar\"",
    "46": "Reprisal \"Resentful Berserk Roar\"",
    "48": "Secret Support \"Possession-Repelling Mentality\"",
    "50": "Secret Support \"Mental Force Expelling the Beasts\"",
    "52": "Haniwa \"Support of the Idol God\"",
    "54": "Haniwa \"Reinforcements of the Idol God\"",
    "56": "Idol Link \"Debut of the Bookworm Idol\"",
    "58": "Idol Link \"Secret Serenade of the Bookworm Idol\"",
    "60": "Square Shape \"Four-Corners Square-Shaped Sculpting Art\"",
    "62": "Square Shape \"Four-Corners Square Creature\"",
    "64": "Circular Shape \"Spread Circle Sculpting Art\"",
    "66": "Circular Shape \"Spread Circle Creature\"",
    "68": "Linear Shape \"Pentagon Line-Shaped Sculpting Art\"",
    "70": "Linear Shape \"Pentagon Linear Creature\"",
    "72": "Haniwa Revival \"Corporal and Horse Rider Idol Sculpting Art\"",
    "74": "Haniwa Revival \"Corporal Idol Creatures\"",
    "76": "\"Chaotic Oni-Shaped Sculpting Art\"",
    "80": "\"Geometric Hexagon Creature\"",
    "84": "\"The Idol Goddess and the Shadow of an Idol\"",
    "137": "Paper Sign \"Dance Scattering Pages\"",
    "139": "Paper Sign \"Wild Dance Scattering Pages\"",
    "165": "Idol Link \"Eternally Bright Blue\"",
    "161": "\"Intertwined Paths of Humans and Objects\""
}