{
    "0": "Wriggle Nightbug \"Meteor on Earth\"",
    "1": "Wriggle Nightbug \"Comet on Earth\"",
    "2": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "3": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "4": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "5": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "6": "Wriggle Nightbug \"Little Bug\"",
    "7": "Wriggle Nightbug \"Little Bug Storm\"",
    "8": "Wriggle Nightbug \"Night Bug Storm\"",
    "9": "Wriggle Nightbug \"Nightbug Tornado\"",
    "10": "Hidden Wriggle Nightbug \"Endless Night Seclusion\"",
    "11": "Hidden Wriggle Nightbug \"Endless Night Seclusion\"",
    "12": "Hidden Wriggle Nightbug \"Endless Night Seclusion\"",
    "13": "Nightmare \"Wild Danmaku Arcanum\"",
    "14": "Nightmare \"Wild Danmaku Arcanum\"",
    "15": "Nightmare \"Wild Danmaku Night Arcanum\"",
    "16": "Nightmare \"Wild Danmaku Night Arcanum\"",
    "17": "Nightmare \"Arrow Barrage\"",
    "18": "Nightmare \"Arrow Barrage\"",
    "19": "Nightmare \"Poison Arrow\"",
    "20": "Nightmare \"Poison Dark Arrow\"",
    "21": "Blackout \"Ill-Starred Dive\"",
    "22": "Blackout \"Ill-Starred Dive\"",
    "23": "Blackout \"Ill-Starred Dive\"",
    "24": "Blackout \"Ill-Starred Dive\"",
    "25": "Blackout \"Darkness Wandering Forever\"",
    "26": "Blackout \"Darkness Wandering Forever\"",
    "27": "Blackout \"Darkness Wandering Forever\"",
    "28": "Blackout \"Darkness Wandering Forever\"",
    "29": "Limit Break \"Total Blackout\"",
    "30": "Limit Break \"Total Blackout\"",
    "31": "Limit Break \"Total Blackout\"",
    "32": "Special Attack \"Tri-Attack\"",
    "33": "Special Attack \"Tri-Attack\"",
    "34": "Special Attack \"Tri-Attack\"",
    "35": "Special Attack \"Tri-Attack\"",
    "36": "Origin Sign \"Throwing Some Familiars on the Wall\"",
    "37": "Origin Sign \"Throwing Some Familiars on the Wall\"",
    "38": "Origin Sign \"Throwing Some Familiars on the Wall\"",
    "39": "Ambition Sign \"Transform\"",
    "40": "Ambition Sign \"Transform\"",
    "41": "Ambition Sign \"Transformra\"",
    "42": "Ambition Sign \"Transformga\"",
    "43": "Tool Sign \"Sword\"",
    "44": "Tool Sign \"Orb\"",
    "45": "Tool Sign \"Mirror\"",
    "46": "Scheme \"Country\"",
    "47": "Ending Sign \"Fake Existence\"",
    "48": "Ending Sign \"Fake Existence\"",
    "49": "Pseudo-History \"The Voyage to Gensokyo\"",
    "50": "Pseudo-History \"The Voyage to Gensokyo\"",
    "51": "Light \"Faith\"",
    "52": "Light \"Salvation\"",
    "53": "Light \"Salvation\"",
    "54": "Darkness \"Duplex Barrier\"",
    "55": "Darkness \"Duplex Barrier\"",
    "56": "Darkness \"Super Duplex Barrier\"",
    "57": "Darkness \"Super Duplex Barrier\"",
    "58": "Darkness \"Fantasy Seal -Spread-\"",
    "59": "Darkness \"Fantasy Seal -Spread-\"",
    "60": "Darkness \"Fantasy Seal -Worn-\"",
    "61": "Darkness \"Fantasy Seal -Worn-\"",
    "62": "Darkness \"Good-Sealing Circle\"",
    "63": "Darkness \"Good-Sealing Circle\"",
    "64": "Darkness \"Omnidirectional Light-Binding Circle\"",
    "65": "Darkness \"Omnidirectional Light-Slaying Circle\"",
    "66": "Darkness \"Fantasy Seal -Concentrate-\"",
    "67": "Darkness \"Fantasy Seal -Concentrate-\"",
    "68": "Darkness \"Fantasy Seal -Marred-\"",
    "69": "Darkness \"Fantasy Seal -Marred-\"",
    "70": "Darkness \"Duplex Danmaku Barrier\"",
    "71": "Darkness \"Duplex Danmaku Barrier\"",
    "72": "Darkness \"Pseudo Danmaku Barrier\"",
    "73": "Darkness \"Pseudo Danmaku Barrier\"",
    "74": "Supreme Darkness \"Fantasy Seal -Blink-\"",
    "75": "Supreme Darkness \"Fantasy Seal -Blink-\"",
    "76": "Supreme Darkness \"Fantasy Seal -Blink-\"",
    "77": "Darkness \"Chaos Stars\"",
    "78": "Darkness \"Chaos Stars\"",
    "79": "Darkness \"Chaos Stars\"",
    "80": "Darkness \"Chaos Stars\"",
    "81": "Darkness \"Stardust Reverie\"",
    "82": "Darkness \"Stardust Reverie\"",
    "83": "Darkness \"Dark Event Horizon\"",
    "84": "Darkness \"Dark Event Horizon\"",
    "85": "Darkness \"Non-Directional Laser\"",
    "86": "Darkness \"Non-Directional Laser\"",
    "87": "Darkness \"Dark Typhoon\"",
    "88": "Darkness \"Dark Typhoon\"",
    "89": "Darkness \"Dark Cannon\"",
    "90": "Darkness \"Dark Cannon\"",
    "91": "Darkness \"Double Dark Cannon\"",
    "92": "Darkness \"Double Dark Cannon\"",
    "93": "Darkness \"Dark Boo Ray\"",
    "94": "Darkness \"Dark Boo Ray\"",
    "95": "Darkness \"Shoot the City\"",
    "96": "Darkness \"Shoot the City\"",
    "97": "Supreme Darkness \"Final Dark Cannon\"",
    "98": "Supreme Darkness \"Final Dark Cannon\"",
    "99": "Supreme Darkness \"Final Dark Cannon of Darkness and Chaos\"",
    "100": "Wave Sign \"Book Hypnosis\"",
    "101": "Wave Sign \"Book Hypnosis\"",
    "102": "Illusion Wave \"Book Hypnosis of Confusion\"",
    "103": "Illusion Wave \"Book Hypnosis of Confusion\"",
    "104": "Book Sign \"Confusing Tuning\"",
    "105": "Book Sign \"Confusing Tuning\"",
    "106": "Book Sign \"Inverse Tuning\"",
    "107": "Book Sign \"Inverse Tuning\"",
    "108": "Magic \"Illusion Stop\"",
    "109": "Magic \"Illusion Stop\"",
    "110": "Magic \"Illusion Stopra\"",
    "111": "Magic \"Illusion Stopga\"",
    "112": "Truth Sign \"Catastrophe\"",
    "113": "Truth Sign \"Catastrophe\"",
    "114": "Truth Sign \"Catastrophe\"",
    "115": "Truth Sign \"Catastrophe\"",
    "116": "Darkness \"Dark Revenge\"",
    "117": "Darkness \"Dark Revenge\"",
    "118": "Darkness \"Dark Revenge\"",
    "119": "Magic \"Zero Gravity\"",
    "120": "Magic \"Zero Gravira\"",
    "121": "Magic \"Zero Graviga\"",
    "122": "Advanced Magic \"Zero Graviza\"",
    "123": "Hidden Remembrance \"Memories of a Certain Genius\"",
    "124": "Hidden Remembrance  \"Memories of a Certain Genius\"",
    "125": "Hidden Remembrance  \"Genius Genealogy\"",
    "126": "Hidden Remembrance  \"Genius Genealogy\"",
    "127": "Hidden Space \"Restricted Space\"",
    "128": "Hidden Space \"Restricted Space\"",
    "129": "Hidden Space \"Restricted Space\"",
    "130": "Hidden Space \"Restricted Red Space\"",
    "131": "Hidden Time \"Omoikane's Device -Clock-\"",
    "132": "Hidden Time \"Omoikane's Device -Clock-\"",
    "133": "Hidden Time \"Omoikane's Brain -Clock-\"",
    "134": "Hidden Time \"Omoikane's Brain -Clock-\"",
    "135": "Hidden Moon \"Apollo 13\"",
    "136": "Hidden Moon \"Apollo 13\"",
    "137": "Hidden Moon \"Apollo 13\"",
    "138": "Hidden Moon \"Apollo 13\"",
    "139": "Hidden Nothingness \"Astronomical Dark Entombing\"",
    "140": "Hidden Nothingness \"Astronomical Dark Entombing\"",
    "141": "Hidden Nothingness \"Astronomical Dark Entombing\"",
    "142": "Hidden Nothingness \"Astronomical Dark Entombing\"",
    "143": "Hidden Rage \"Rage Awakened -Expulsion-\"",
    "144": "Hidden Rage \"Rage Awakened -Expusion-\"",
    "145": "Hidden Rage \"Rage Awakened -Expulsion-\"",
    "146": "Hidden Rage \"Rage Awakened -Expulsion-\"",
    "147": "Magic \"Magnet\"",
    "148": "Magic \"Magnet\"",
    "149": "Magic \"Magnera\"",
    "150": "Magic \"Magnega\"",
    "151": "Light \"Prism Windmill\"",
    "152": "Light \"Prism Windmill\"",
    "153": "Light \"Great Prism Windmill\"",
    "154": "Light \"Great Prism Windmill\"",
    "155": "Light Magic \"Spark\"",
    "156": "Light Magic \"Spark\"",
    "157": "Light Magic \"Sparkra\"",
    "158": "Advanced Light Magic \"Sparkga\"",
    "159": "Blazing Sign \"Raging Wave\"",
    "160": "Blazing Sign \"Raging Wave\"",
    "161": "Blazing Sign \"Raging Storm\"",
    "162": "Blazing Sign \"Raging Storm\"",
    "163": "Light \"Holy Burst\"",
    "164": "Light \"Holy Burst\"",
    "165": "Filop \"Inverse Burst\"",
    "166": "Filop \"Inverse Burst\"",
    "167": "Limit Break \"Prism Rain\"",
    "168": "Limit Break \"Prism Rain\"",
    "169": "Final Limit \"Prism Storm\"",
    "170": "Final Limit \"Prism Storm\"",
    "171": "\"Pure Furies Over Time -New Moon-\"",
    "172": "\"Pure Furies Over Time -Crescent Moon-\"",
    "173": "\"Pure Furies Over Time -1st Quarter's Moon-\"",
    "174": "\"Pure Furies Over Time -Matsuyoi-\"",
    "175": "\"Pure Furies Over Time -11 o'Clock-\"",
    "176": "\"Pure Furies Over Time -Half to Midnight-\"",
    "177": "\"Pure Furies Over Time -Midnight-\"",
    "178": "\"Pure Furies Over Time -Half After Midnight-\"",
    "179": "\"Pure Furies Over Time -1 o'Clock-\"",
    "180": "\"Pure Furies Over Time -Half After 1-\"",
    "181": "\"Pure Furies Over Time -Dead of Night-\"",
    "182": "\"Pure Furies Over Time -Half After 2-\"",
    "183": "\"Pure Furies Over Time -3 o'Clock-\"",
    "184": "\"Pure Furies Over Time -Half After 3-\"",
    "185": "\"Pure Furies Over Time -4 o'Clock-\"",
    "186": "\"Pure Furies Over Time -Half After 4-\"",
    "187": "\"Pure Furies Over Time -Morning Mist-\"",
    "188": "\"Pure Furies Over Time -Dawn-\"",
    "189": "\"Pure Furies Over Time -Morning Star-\"",
    "190": "\"Pure Furies Over Time -Rising World-\"",
    "191": "Defense \"Dual Wielding Cave\"",
    "192": "Filop \"Behind You\"",
    "193": "Attack \"Dual Wielding Cave\"",
    "194": "Battle Start \"Treasonous Knives\"",
    "195": "Immortal \"Fire Bird -Flying Phoenix-\"",
    "196": "Return \"Bouncing Amulets\"",
    "197": "Test \"No This Is Not Nazi\"",
    "198": "Sweep \"Does This Laser Really Sweep?\"",
    "199": "Familiars \"Woo I'm a Ghost\"",
    "200": "Magic \"Fire Wall\"",
    "201": "Advanced Magic \"Firetooth\"",
    "202": "\"Possessed by the Book\"",
    "203": "\"Confusion Ending\"",
    "204": "\"Auto-Life Shooting\"",
    "205": "\"Unseasonal Butterfly Storm\"",
    "206": "\"Nightmare Blackout\"",
    "207": "\"Nightmarish Abyss\"",
    "208": "\"Fast Catastrophe\"",
    "209": "\"Hidden Star in Nothingness\"",
    "210": "\"Ragnarok\"",
    "211": "\"Phoenix Rebirth\"",
    "212": "\"Ancient Duper\"",
    "213": "\"Behind You!!\"",
    "214": "\"Fantasy Dark Nature\"",
    "215": "\"Dark Rush\""
}
