{
    "0": "Wriggle Nightbug \"Meteor on Earth\"",
    "1": "Wriggle Nightbug \"Comet on Earth\"",
    "2": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "3": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "4": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "5": "Wriggle Nightbug \"Firefly Phenomenon\"",
    "6": "Wriggle Nightbug \"Little Bug\"",
    "7": "Wriggle Nightbug \"Little Bug Storm\"",
    "8": "Wriggle Nightbug \"Night Bug Storm\"",
    "9": "Wriggle Nightbug \"Nightbug Tornado\"",
    "10": "Hidden Wriggle Nightbug \"Endless Night Seclusion\"",
    "11": "Hidden Wriggle Nightbug \"Endless Night Seclusion\"",
    "12": "Hidden Wriggle Nightbug \"Endless Night Seclusion\"",
    "13": "Nightmare Sign \"Wild Danmaku Arcanum\"",
    "14": "Nightmare Sign \"Wild Danmaku Arcanum\"",
    "15": "Nightmare Sign \"Wild Danmaku Night Arcanum\"",
    "16": "Nightmare Sign \"Wild Danmaku Night Arcanum\"",
    "17": "Nightmare Sign \"Arrow Barrage\"",
    "18": "Nightmare Sign \"Arrow Barrage\"",
    "19": "Nightmare Sign \"Poison Arrow\"",
    "20": "Nightmare Sign \"Poison Dark Arrow\"",
    "21": "Blackout \"Dark Dive\"",
    "22": "Blackout \"Dark Dive\"",
    "23": "Blackout \"Dark Dive\"",
    "24": "Blackout \"Dark Dive\"",
    "25": "Blackout \"Darkness Wandering Forever\"",
    "26": "Blackout \"Darkness Wandering Forever\"",
    "27": "Blackout \"Darkness Wandering Forever\"",
    "28": "Blackout \"Darkness Wandering Forever\"",
    "29": "Limit Break \"Total Blackout\"",
    "30": "Limit Break \"Total Blackout\"",
    "31": "Limit Break \"Total Blackout\"",
    "32": "Trinity \"First Trinity\"",
    "33": "Trinity \"First Trinity\"",
    "34": "Trinity \"First Trinity\"",
    "35": "Trinity \"First Trinity\"",
    "36": "Kamikaze \"Devices Rushing at the Wall\"",
    "37": "Kamikaze \"Devices Rushing at the Wall\"",
    "38": "Kamikaze \"Devices Rushing at the Wall\"",
    "39": "Bullet Maze \"Petal Attack\"",
    "40": "Bullet Maze \"Petal Attack\"",
    "41": "Bullet Metamorphosis \"Transform\"",
    "42": "Bullet Metamorphosis \"Transformga\"",
    "43": "Strike \"Quick Danmaku Blitz\"",
    "44": "Strike \"Sliding Bullet Dash\"",
    "45": "Magic Sign \"Wall Reflera\"",
    "46": "Ice Sign \"Danmaku Icebreaker\"",
    "47": "Outcast Sign \"Fake Existence\"",
    "48": "Outcast Sign \"Fake Existence\"",
    "49": "Outcast Sign \"The Voyage to Gensokyo\"",
    "50": "Outcast Sign \"The Voyage to Gensokyo\"",
    "51": "Light \"Secret Past\"",
    "52": "Light \"Absolute Present\"",
    "53": "Light \"Hidden Future\"",
    "54": "Darkness Sign \"Dark Wall\"",
    "55": "Darkness Sign \"Dark Wall\"",
    "56": "Darkness Sign \"Super Dark Wall\"",
    "57": "Darkness Sign \"Super Dark Wall\"",
    "58": "Darkness Sign \"Helm Split\"",
    "59": "Darkness Sign \"Helm Split\"",
    "60": "Darkness Sign \"Helm Split\"",
    "61": "Darkness Sign \"Helm Split\"",
    "62": "Darkness Sign \"Maelstrom\"",
    "63": "Darkness Sign \"Maelstrom\"",
    "64": "Darkness Sign \"Dark Maelstrom\"",
    "65": "Darkness Sign \"Dark Maelstrom\"",
    "66": "Darkness Sign \"Barrage\"",
    "67": "Darkness Sign \"Barrage\"",
    "68": "Darkness Sign \"Dark Barrage\"",
    "69": "Darkness Sign \"Dark Barrage\"",
    "70": "Darkness Sign \"Space Break\"",
    "71": "Darkness Sign \"Space Break\"",
    "72": "Darkness Sign \"Dark Space Break\"",
    "73": "Darkness Sign \"Dark Space Break\"",
    "74": "Supreme Darkness \"Dark Aura\"",
    "75": "Supreme Darkness \"Dark Aura\"",
    "76": "Supreme Darkness \"Dark Aura\"",
    "77": "Darkness Sign \"Chaos Stars\"",
    "78": "Darkness Sign \"Chaos Stars\"",
    "79": "Darkness Sign \"Chaos Stars\"",
    "80": "Darkness Sign \"Chaos Stars\"",
    "81": "Darkness Sign \"Dark Reverie\"",
    "82": "Darkness Sign \"Dark Reverie\"",
    "83": "Darkness Sign \"Dark Event Horizon\"",
    "84": "Darkness Sign \"Dark Event Horizon\"",
    "85": "Darkness Sign \"Non-Directional Dark Laser\"",
    "86": "Darkness Sign \"Non-Directional Dark Laser\"",
    "87": "Darkness Sign \"Dark Typhoon\"",
    "88": "Darkness Sign \"Dark Typhoon\"",
    "89": "Darkness Sign \"Dark Cannon\"",
    "90": "Darkness Sign \"Dark Cannon\"",
    "91": "Darkness Sign \"Double Dark Cannon\"",
    "92": "Darkness Sign \"Double Dark Cannon\"",
    "93": "Darkness Sign \"Dark Boo Ray\"",
    "94": "Darkness Sign \"Dark Boo Ray\"",
    "95": "Darkness Sign \"Shoot the City\"",
    "96": "Darkness Sign \"Shoot the City\"",
    "97": "Supreme Darkness \"Final Dark Cannon\"",
    "98": "Supreme Darkness \"Final Dark Cannon\"",
    "99": "Supreme Darkness \"Absolutely Ultimate Dark Cannon\"",
    "100": "Wave Sign \"Book Hypnosis\"",
    "101": "Wave Sign \"Book Hypnosis\"",
    "102": "Illusion Wave \"Book Hypnosis of Confusion\"",
    "103": "Illusion Wave \"Book Hypnosis of Confusion\"",
    "104": "Book Sign \"Confusing Tuning\"",
    "105": "Book Sign \"Confusing Tuning\"",
    "106": "Book Sign \"Inverse Tuning\"",
    "107": "Book Sign \"Inverse Tuning\"",
    "108": "Magic Sign \"Illusion Stop\"",
    "109": "Magic Sign \"Illusion Stop\"",
    "110": "Magic Sign \"Illusion Stopra\"",
    "111": "Magic Sign \"Illusion Stopga\"",
    "112": "Truth Sign \"Catastrophe\"",
    "113": "Truth Sign \"Catastrophe\"",
    "114": "Truth Sign \"Catastrophe\"",
    "115": "Truth Sign \"Catastrophe\"",
    "116": "Darkness Sign \"Dark Revenge\"",
    "117": "Darkness Sign \"Dark Revenge\"",
    "118": "Darkness Sign \"Dark Revenge\"",
    "119": "Magic Sign \"Zero Gravity\"",
    "120": "Magic Sign \"Zero Gravira\"",
    "121": "Magic Sign \"Zero Graviga\"",
    "122": "Advanced Magic \"Zero Graviza\"",
    "123": "Hidden Remembrance \"Memories of the Secret God\"",
    "124": "Hidden Remembrance  \"Memories of the Absolute Secret God\"",
    "125": "Hidden Remembrance  \"Genealogy of the Secret God\"",
    "126": "Hidden Remembrance  \"Genealogy of the Absolute Secret God\"",
    "127": "Hidden Space \"Restricted Space\"",
    "128": "Hidden Space \"Restricted Space\"",
    "129": "Hidden Space \"Restricted Space\"",
    "130": "Hidden Space \"Restricted Red Space\"",
    "131": "Hidden Time \"Experience over Time\"",
    "132": "Hidden Time \"Experience over Time\"",
    "133": "Hidden Time \"Experience over Hours\"",
    "134": "Hidden Time \"Experience over Hours\"",
    "135": "Hidden Moon \"Apollo XIII\"",
    "136": "Hidden Moon \"Apollo XIII\"",
    "137": "Hidden Moon \"Apollo XIII\"",
    "138": "Hidden Moon \"Apollo XIII\"",
    "139": "Hidden Nothingness \"Transcendance\"",
    "140": "Hidden Nothingness \"Transcendance\"",
    "141": "Hidden Nothingness \"Transcendance\"",
    "142": "Hidden Nothingness \"Transcendance\"",
    "143": "Expulsion \"Hidden Rage Awakened\"",
    "144": "Expulsion \"Hidden Rage Awakened\"",
    "145": "Expulsion \"Hidden Rage Awakened\"",
    "146": "Expulsion \"Hidden Rage Awakened\"",
    "147": "Magic \"Magnet\"",
    "148": "Magic \"Magnet\"",
    "149": "Magic \"Magnera\"",
    "150": "Magic \"Magnega\"",
    "151": "Light Sign \"Prism Windmill\"",
    "152": "Light Sign \"Prism Windmill\"",
    "153": "Light Sign \"Great Prism Windmill\"",
    "154": "Light Sign \"Great Prism Windmill\"",
    "155": "Light Magic \"Spark\"",
    "156": "Light Magic \"Spark\"",
    "157": "Light Magic \"Sparkra\"",
    "158": "Advanced Light Magic \"Sparkga\"",
    "159": "Fire Magic \"Raging Wave\"",
    "160": "Fire Magic \"Raging Wave\"",
    "161": "Fire Magic \"Raging Storm\"",
    "162": "Fire Magic \"Raging Storm\"",
    "163": "Front Sign \"Halo of the Human\"",
    "164": "Front Sign \"Halo of the Human\"",
    "165": "Back Sign \"Halo of the Nobody\"",
    "166": "Back Sign \"Halo of the Nobody\"",
    "167": "Limit Break \"Prism Rain\"",
    "168": "Limit Break \"Prism Rain\"",
    "169": "Final Limit \"Prism Storm\"",
    "170": "Final Limit \"Prism Storm\"",
    "171": "\"Way to the Dawn -New Moon-\"",
    "172": "\"Way to the Dawn -Crescent Moon-\"",
    "173": "\"Way to the Dawn -1st Quarter's Moon-\"",
    "174": "\"Way to the Dawn -Matsuyoi-\"",
    "175": "\"Way to the Dawn -11 o'Clock-\"",
    "176": "\"Way to the Dawn -Half to Midnight-\"",
    "177": "\"Way to the Dawn -Midnight-\"",
    "178": "\"Way to the Dawn -Half After Midnight-\"",
    "179": "\"Way to the Dawn -1 o'Clock-\"",
    "180": "\"Way to the Dawn -Half After 1-\"",
    "181": "\"Way to the Dawn -Dead of Night-\"",
    "182": "\"Way to the Dawn -Half After 2-\"",
    "183": "\"Way to the Dawn -3 o'Clock-\"",
    "184": "\"Way to the Dawn -Half After 3-\"",
    "185": "\"Way to the Dawn -4 o'Clock-\"",
    "186": "\"Way to the Dawn -Half After 4-\"",
    "187": "\"Way to the Dawn -Morning Mist-\"",
    "188": "\"Way to the Dawn -Dawn-\"",
    "189": "\"Way to the Dawn -Morning Star-\"",
    "190": "\"Way to the Dawn -Rising World-\"",
    "191": "First Duel \"Impulse\"",
    "192": "Second Duel \"Maelstrom\"",
    "193": "Final Duel \"Barrage\"",
    "194": "Reversal \"Treasonous Knives\"",
    "195": "Fire Bird \"Flying Moltres\"",
    "196": "Reversal \"Bouncing Amulets\"",
    "197": "Corner \"Amulet Walls\"",
    "198": "Honest Death \"Illusionary Deadly Laser\"",
    "199": "Devices \"Sliding Devices\"",
    "200": "Fire Magic \"Fire Wall\"",
    "201": "Advanced Fire Magic \"Firetooth\"",
    "202": "\"Aura Possession\"",
    "203": "\"Anarchy Spiral Hell\"",
    "204": "\"Ultimate Auto-Life\"",
    "205": "Wriggle Nightbug \"Unseasonal Butterfly Storm\"",
    "206": "\"Nightmare Blackout\"",
    "207": "\"Nightmarish Abyss\"",
    "208": "\"Fast Catastrophe\"",
    "209": "\"Hidden Star in Nothingness\"",
    "210": "\"Prism Ragnarok\"",
    "211": "\"Flying Ho-Oh\"",
    "212": "\"Dark Link\"",
    "213": "\"Darkest Maelstrom\"",
    "214": "\"Absolute Dark Aura\"",
    "215": "\"Dark Rush\""
}
