{
    "0": "Rumia \"Moonlight Ray\"",
    "1": "Rumia \"Night Bird\"",
    "2": "Rumia \"Demarcation\"",
    "3": "Piercing Chill \"Icicle Fall\"",
    "4": "Piercing Chill \"Hailstorm\"",
    "5": "Piercing Chill \"Perfect Freeze\"",
    "6": "Piercing Chill \"Diamond Blizzard\"",
    "7": "Nightmare \"Spreading Nightmare\"",
    "8": "Nightmare \"Tormenting Flower\"",
    "9": "Nightmare \"Dark Blizzard\"",
    "10": "Illusion Sign \"Eternal Illusion\"",
    "11": "Chaos Sign \"Scissor Bite\"",
    "12": "Chaos Sign \"Scissor Chaotic Bite\"",
    "13": "Melee \"Wild Arcanum\"",
    "14": "Fire Snatch \"Agni Shine\"",
    "15": "Water Snatch \"Princess Undine\"",
    "16": "Wood Snatch \"Sylphae Horn\"",
    "17": "Earth Snatch \"Rage Trilithon\"",
    "18": "Metal Snatch \"Metal Fatigue\"",
    "19": "Fire Snatch \"Agni Shine High Level\"",
    "20": "Wood Snatch \"Sylphae Horn High Level\"",
    "21": "Earth Snatch \"Rage Trilithon High Level\"",
    "22": "Fire Snatch \"Agni Radiance\"",
    "23": "Water Snatch \"Bury In Lake\"",
    "24": "Wood Snatch \"Green Storm\"",
    "25": "Earth Snatch \"Trilithon Shake\"",
    "26": "Metal Snatch \"Silver Dragon\"",
    "27": "Fire & Earth Snatch \"Lava Cromlech\"",
    "28": "Wood & Fire Snatch \"Forest Blaze\"",
    "29": "Water & Wood Snatch \"Water Elf\"",
    "30": "Metal & Water Snatch \"Mercury Poison\"",
    "31": "Earth & Metal Snatch \"Emerald Megalith\"",
    "32": "Conjuring \"Misdirection\"",
    "33": "Conjuring \"Illusional Misdirection\"",
    "34": "Illusion Existence \"Clock Corpse\"",
    "35": "Illusion Image \"Luna Clock\"",
    "36": "Maid Secret Skill \"Puppet Doll\"",
    "37": "Illusion Phantom \"Jack the Ludo Bile\"",
    "38": "Illusion World \"The World\"",
    "39": "Maid Secret Skill \"Killing Doll\"",
    "40": "Conjuring \"Eternal Meek\"",
    "41": "Darkness \"Omni Laser\"",
    "42": "Ice Sign \"Dark Red Blizzard\"",
    "43": "Darkness \"Dark Chaos\"",
    "44": "Dark Sign \"Dark Shoot\"",
    "45": "\"Dark Magic\"",
    "46": "Divine Punishment \"Chaotic Omni Laser\"",
    "47": "Ice Sign \"Dark Red Blizzaga\"",
    "48": "Darkness \"Dark Illusion\"",
    "49": "Darkness \"Dark Overflow\"",
    "50": "\"Dark Gensokyo\"",
    "51": "Moon Snatch \"Silent Selene\"",
    "52": "Sun Snatch \"Royal Flare\"",
    "53": "Fire Water Wood Metal Earth Snatch \"Philosopher's Stone\"",
    "54": "Taboo \"Cranberry Trap\"",
    "55": "Taboo \"Lævateinn\"",
    "56": "Taboo \"Four of a Kind\"",
    "57": "Taboo \"Kagome, Kagome\"",
    "58": "Taboo \"Maze of Love\"",
    "59": "Forbidden Barrage \"Starbow Break\"",
    "60": "Forbidden Barrage \"Catadioptric\"",
    "61": "Forbidden Barrage \"Clock that Ticks Away the Past\"",
    "62": "Secret Barrage \"And Then Will There Be None?\"",
    "63": "Q.E.D. \"Ripples of 495 Years\""
}
