{
    "0": "Rumia \"Moonlight Ray\"",
    "1": "Rumia \"Night Bird\"",
    "2": "Rumia \"Demarcation\"",
    "3": "Piercing Chill \"Icicle Fall\"",
    "4": "Piercing Chill \"Hailstorm\"",
    "5": "Piercing Chill \"Perfect Freeze\"",
    "6": "Piercing Chill \"Diamond Blizzard\"",
    "7": "Nightmare \"Spreading Nightmare\"",
    "8": "Nightmare \"Tormenting Flower\"",
    "9": "Nightmare \"Dark Blizzard\"",
    "10": "Illusion Sign \"Eternal Illusion\"",
    "11": "Chaos Sign \"Scissor Bite\"",
    "12": "Chaos Sign \"Scissor Chaotic Bite\"",
    "13": "Melee \"Wild Arcanum\"",
    "14": "Fire Snatch \"Agni Shine\"",
    "15": "Water Snatch \"Princess Undine\"",
    "16": "Wood Snatch \"Sylphae Horn\"",
    "17": "Earth Snatch \"Rage Trilithon\"",
    "18": "Metal Snatch \"Metal Fatigue\"",
    "19": "Fire Snatch \"Agni Shine High Level\"",
    "20": "Wood Snatch \"Sylphae Horn High Level\"",
    "21": "Earth Snatch \"Rage Trilithon High Level\"",
    "22": "Fire Snatch \"Agni Radiance\"",
    "23": "Water Snatch \"Bury In Lake\"",
    "24": "Wood Snatch \"Green Storm\"",
    "25": "Earth Snatch \"Trilithon Shake\"",
    "26": "Metal Snatch \"Silver Dragon\"",
    "27": "Fire & Earth Snatch \"Lava Cromlech\"",
    "28": "Wood & Fire Snatch \"Forest Blaze\"",
    "29": "Water & Wood Snatch \"Water Elf\"",
    "30": "Metal & Water Snatch \"Mercury Poison\"",
    "31": "Earth & Metal Snatch \"Emerald Megalith\"",
    "32": "Misdirection \"Teleport Lock\"",
    "33": "Misdirection \"Teleport Illusionary Lock\"",
    "34": "Zero Shot \"Clock Shot\"",
    "35": "Zero Shot \"Clock Dense Shot\"",
    "36": "Zero Shot\"Clock Redirect\"",
    "37": "Zero Shot \"Illusionary Block\"",
    "38": "Zero Shot \"The World\"",
    "39": "Zero Shot \"Time Reversal\"",
    "40": "\"Eternal Despair\"",
    "41": "Darkness \"Omni Laser\"",
    "42": "Ice Sign \"Dark Red Blizzard\"",
    "43": "Darkness \"Dark Chaos\"",
    "44": "Dark Sign \"Dark Shot\"",
    "45": "\"Dark Magic\"",
    "46": "Darkness \"Chaotic Omni Laser\"",
    "47": "Ice Sign \"Dark Red Blizzaga\"",
    "48": "Darkness \"Dark Illusion\"",
    "49": "Darkness \"Dark Overflow\"",
    "50": "\"Dark Gensokyo\"",
    "51": "Moon Snatch \"Silent Selene\"",
    "52": "Sun Snatch \"Royal Flare\"",
    "53": "Fire Water Wood Metal Earth Snatch \"Philosopher's Stone\"",
    "54": "Darkness \"Bullet Trap\"",
    "55": "Darkness \"Screen Split\"",
    "56": "Darkness \"Self Misplacement\"",
    "57": "Darkness \"Kick Wave\"",
    "58": "Darkness \"Dark Maze\"",
    "59": "Forbidden Darkness \"Charge Crash\"",
    "60": "Forbidden Darkness \"Dark Shot Reflega\"",
    "61": "Forbidden Darkness \"Distortion of Space and Time\"",
    "62": "\"Creeping Darkness\"",
    "63": \"Dark Ripples\""
}
