{
    "44": "Evil Sign \"Yang Xaogui\"",
    "45": "Evil Sign \"Guhún Yegui\"",
    "47": "Demonify \"Zouhuo Rùmó\"",
    "51": "Possession \"Corpse Tóngji\"",
    "53": "Spirit Link \"Tonglíng Yoshika\"",
    "59": "Book Sign \"Maze of a Hundred Pages\"",
    "60": "Book Sign \"Maze of a Hundred Pages\"",
    "61": "Book Sign \"Maze of a Thousand Pages\"",
    "62": "Snipe Sign \"Sharp Shooting\"",
    "64": "Snipe Sign \"Relentless Sharp Shooting\"",
    "66": "Moon Berserk \"Wrath of the Rear Face\"",
    "68": "Moon Berserk \"Merciless Furies of the Back\"",
    "70": "Illusion Sign \"Concealed in Four Book Barriers\"",
    "72": "Illusion Sign \"Concealed in Four Book Barriers\"",
    "74": "Shotlock \"Starry Hindrance\"",
    "123": "Book Sign \"Maze of a Million Pages\"",
    "124": "Final Limit \"The Ultimate, Absolute Skill Rush\"",
    "155": "\"Enduring the Flow of Time Until the End\"",
    "161": "\"Starry Sky of Lingering Desires\""
}