{
    "44": "Evil Sign \"Yang Xaogui\"",
    "45": "Evil Sign \"Guhún Yegui\"",
    "47": "Demonify \"Zouhuo Rùmó\"",
    "51": "Possession \"Corpse Tóngji\"",
    "53": "Spirit Link \"Tonglíng Yoshika\"",
    "59": "Book Sign \"Maze of a Hundred Pages\"",
    "60": "Book Sign \"Maze of a Hundred Pages\"",
    "61": "Book Sign \"Maze of a Thousand Pages\"",
    "62": "Gun Sign \"Sharp Shooting\"",
    "64": "Gun Sign \"Relentless Sharp Shooting\"",
    "66": "Moon Sign \"Wrath of the Rear Face\"",
    "68": "Moon Sign \"Merciless Furies of the Back\"",
    "70": "Illusion Sign \"Concealed in Four Book Barriers\"",
    "72": "Illusion Sign \"Concealed in Four Book Barriers\"",
    "74": "Star Sign \"Stellar Hindrance\"",
    "123": "Book Sign \"Maze of a Million Pages\"",
    "124": "\"The Ultimate, Absolute Skill Rush\"",
    "155": "Time Link \"Endure the Imperishable Flow of Time\"",
    "161": "\"Starry Sky of Lingering Desires\""
}