{
    "0": "Shizuha Aki \"Falling Leaves of Madness\"",
    "2": "Hidden Fall \"Dark Sky\"",
    "4": "Hidden Fall \"The Hidden Dark Season\"",
    "6": "Hidden Fall \"Dark Radiance\"",
    "8": "Hidden Fall \"Bright Feeble Darkness\"",
    "10": "Nightmare Sign \"Nightmarish Fortune\"",
    "12": "Nightmare Sign \"Nightmarish Misfortune\"",
    "14": "Flawed Sign \"Broken Dream\"",
    "16": "Scar \"Broken Charm of Dreams\"",
    "18": "Evil Spirit \"Nightmarish Wheel\"",
    "20": "Nightmare Sign \"Dark Firaga\"",
    "22": "Nightmare Sign \"Torment Flow\"",
    "24": "Nightmare Sign \"Exiled Dream\"",
    "26": "Wisdom Form \"Water Illusion\"",
    "28": "Wisdom Form \"Water Mirage\"",
    "30": "Water Magic \"Surf\"",
    "32": "Water Magic \"Great Wave\"",
    "33": "Water Magic \"Deep Drown\"",
    "34": "Water Magic \"Waterfall\"",
    "36": "Water Magic \"Flash Flood\"",
    "37": "Water Magic \"Great Illusionary Waterfall\"",
    "38": "Light Sign \"Green Radiance\"",
    "40": "Light Sign \"Exteeeending Green Radiance\"",
    "41": "Spinning 360s \"Shock Slash\"",
    "42": "Shooting \"Falling Bullets\"",
    "44": "Shooting \"Falling Reflected Bullets\"",
    "46": "Wind Shot \"Magnet and Shoot\"",
    "48": "Wind Shot \"Magnera and Shoot\"",
    "49": "Wind Shot \"Shooting Tornado\"",
    "50": "\"Time and Space Trick\"",
    "51": "\"Time and Space Trick\"",
    "52": "\"Peerless Space Manipulator\"",
    "53": "Sleep \"Sleep Procession\"",
    "55": "Sleepra \"Nightmare-Inducing Shots\"",
    "56": "Sleepga \"Remembrance Nightmare\"",
    "57": "Remembrance \"Gray Thaumaturgy\"",
    "59": "Remembrance \"Forgotten Ritual\"",
    "60": "Remembrance \"Secretly Inherited Art of Danmaku\"",
    "61": "Remembrance \"Daytime Guest Stars\"",
    "63": "Remembrance \"Night with Bright Guest Stars\"",
    "64": "Remembrance \"Night with Overly Bright Guest Stars\"",
    "65": "Remembrance \"The Day the Sea Split\"",
    "67": "Remembrance \"Moses's Miracle\"",
    "68": "Remembrance \"Moses's Miracle\"",
    "69": "Remembrance \"Star Ritual to Call the Godly Winds\"",
    "71": "Remembrance \"Summon Takeminakata\"",
    "73": "Awakening \"Drop-Me-Not\"",
    "75": "Awakening \"Drop-Me-Never\"",
    "77": "Throwing \"Tower Throw\"",
    "79": "Throwing \"Catastrophe Tower Throw\"",
    "80": "Throwing \"Catastrophe Tower Throw\"",
    "81": "Shot \"Interdiction Barrage -Lv.1-\"",
    "82": "Shot \"Interdiction Barrage -Lv.2-\"",
    "83": "Shot \"Interdiction Barrage -Lv.3-\"",
    "84": "Shot \"Interdiction Barrage -Lv.MAX-\"",
    "85": "Nothingness \"Energy Orb\"",
    "87": "Nothingness \"Warp Flying Swords\"",
    "88": "Nothingness \"Warp Double Flying Swords\"",
    "89": "Thunder Fall \"Spark Wall\"",
    "91": "Thunder Storm \"Spark Storm\"",
    "93": "\"Invitation to Nothingness\"",
    "95": "\"Invitation to Eternal Nothingness\"",
    "97": "Nothingness \"Shot Barrage\"",
    "98": "Nothingness \"Gathering Hearts\"",
    "99": "Nothingness \"Drop Shot\"",
    "100": "Back Sign \"Fake Back Door Shot\"",
    "101": "Light Sign \"Reflected Light\"",
    "102": "Rings \"Circle Raid\"",
    "103": "Shotlock \"Cornering Lanes\"",
    "104": "Quake \"Broken Bullets\"",
    "105": "Secret God \"Seven Swords and Seven Stars\"",
    "106": "Back Sign \"Back Waterfall\"",
    "107": "Final Form \"Sonic Blade\"",
    "108": "Final Form \"Fiction War - Canon Vs. Not Canon\"",
    "109": "\"Hidden Rage Awakened -Green Phase-\""
}
