{
    "0": "Shizuha Aki \"Falling Leaves of Madness\"",
    "2": "Minoriko Aki \"Fall Sky\"",
    "4": "Minoriko Aki \"The Fall Sky and a Maiden's Heart\"",
    "6": "Minoriko Aki \"Owotoshi Harvester\"",
    "8": "Minoriko Aki \"Promise of the Wheat God\"",
    "10": "Nightmare \"Nightmarish Fortune\"",
    "12": "Nightmare \"Nightmarish Misfortune\"",
    "14": "Flawed Sign \"Broken Dream\"",
    "16": "Scar \"Broken Charm of Dreams\"",
    "18": "Evil Spirit \"Nightmarish Wheel\"",
    "20": "Nightmare \"Dark Firaga\"",
    "22": "Nightmare \"Pain Flow\"",
    "24": "Nightmare \"Exiled Dream\"",
    "26": "Wisdom Form \"Optical Camouflage\"",
    "28": "Wisdom Form \"Hydro Camouflage\"",
    "30": "Water \"Ooze Flooding\"",
    "32": "Water \"Diluvial Mere\"",
    "33": "Water \"Trauma in the Glimmering Depths\"",
    "34": "Water Sign \"Waterfall\"",
    "36": "Water Sign \"Flash Flood\"",
    "37": "Water Sign \"Great Illusionary Waterfall\"",
    "38": "Light \"Green Radiance\"",
    "40": "Light \"Exteeeending Green Radiance\"",
    "41": "Spinning 360s \"Shock Slash\"",
    "42": "Shooting \"Falling Bullets\"",
    "44": "Shooting \"Falling Reflected Bullets\"",
    "46": "Wind Shot \"Magnet and Shoot\"",
    "48": "Wind Shot \"Magnera and Shoot\"",
    "49": "Wind Shot \"Shooting Tornado\"",
    "50": "\"Time and Space Trick\"",
    "51": "\"Time and Space Trick\"",
    "52": "\"Peerless Space Manipulator\"",
    "53": "Sleep \"Sleep Procession\"",
    "55": "Sleepra \"Nightmare-Inducing Shots\"",
    "56": "Sleepga \"Remembrance Nightmare\"",
    "57": "Remembrance \"Gray Thaumaturgy\"",
    "59": "Remembrance \"Forgotten Ritual\"",
    "60": "Remembrance \"Secretly Inherited Art of Danmaku\"",
    "61": "Remembrance \"Daytime Guest Stars\"",
    "63": "Remembrance \"Night with Bright Guest Stars\"",
    "64": "Remembrance \"Night with Overly Bright Guest Stars\"",
    "65": "Remembrance \"The Day the Sea Split\"",
    "67": "Remembrance \"Moses's Miracle\"",
    "68": "Remembrance \"Moses's Miracle\"",
    "69": "Remembrance \"Star Ritual to Call the Godly Winds\"",
    "71": "Remembrance \"Summon Takeminakata\"",
    "73": "Awakening \"Drop-Me-Not\"",
    "75": "Awakening \"Drop-Me-Never\"",
    "77": "Throwing \"Tower Throw\"",
    "79": "Throwing \"Catastrophe Tower Throw\"",
    "80": "Throwing \"Catastrophe Tower Throw\"",
    "81": "Shot \"Interdiction Barrage -Lv.1-\"",
    "82": "Shot \"Interdiction Barrage -Lv.2-\"",
    "83": "Shot \"Interdiction Barrage -Lv.3-\"",
    "84": "Shot \"Interdiction Barrage -Lv.MAX-\"",
    "85": "Nothingness \"Energy Orb\"",
    "87": "Nothingness \"Warp Flying Swords\"",
    "88": "Nothingness \"Warp Double Flying Swords\"",
    "89": "Thunder Fall \"Spark Wall\"",
    "91": "Thunder Storm \"Spark Storm\"",
    "93": "\"Invitation to Nothingness\"",
    "95": "\"Invitation to Eternal Nothingness\"",
    "97": "Nothingness \"Shot Barrage\"",
    "98": "Nothingness \"Gathering Hearts\"",
    "99": "Nothingness \"Drop Shot\"",
    "100": "Battle Start \"Weren't You Behind Me?\"",
    "101": "Light \"Reflected Light\"",
    "102": "Ability \"Circle Raid\"",
    "103": "Shotlock \"Cornering Lanes\"",
    "104": "Quake \"Broken Bullets\"",
    "105": "Bind \"Seven Stones and Seven Bind Columns\"",
    "106": "Wisdom Form \"Illusionary Waterfall\"",
    "107": "Final Form \"Sonic Blade\"",
    "108": "Final Form \"Fiction War - Canon Vs. Not Canon\"",
    "109": "Hidden Rage \"Rage Awakened -Green Phase-\""
}
