{
    "0": "Seiran \"Speed Strike\"",
    "2": "Seiran \"Eagle Shooting\"",
    "5": "Seiran \"The Eagle Shot Its Target\"",
    "6": "Seiran \"Lunatic Gun\"",
    "9": "Seiran \"Lunatic Gun\"",
    "10": "Glitch Sign \"Spreading Glitch\"",
    "12": "Glitch Sign \"Spreading Double Glitch\"",
    "14": "Glitch Sign \"Glitch Reflect\"",
    "16": "Glitch Sign \"Glitch Reflera\"",
    "17": "Glitch Sign \"Glitch Reflega\"",
    "18": "Glitch Sign \"Chaotic Glitch\"",
    "21": "Glitch Sign \"Lunatic Glitch\"",
    "22": "Nightmare Sign \"Scissor Bite\"",
    "24": "Nightmare Sign \"Oppressive Scissor Bite\"",
    "26": "Nightmare Sign \"Poison Arrow\"",
    "28": "Nightmare Sign \"Three Poison Arrows Combo\"",
    "29": "Nightmare Sign \"Eternal Poison Arrows Combo\"",
    "30": "Nightmare Sign \"Ochre Wandering\"",
    "32": "Nightmare Sign \"Ochre Labyrinthine Wandering\"",
    "34": "Nightmare Sign \"Shadow Stealer\"",
    "36": "Nightmare Sign \"Azure Shadow Stealer\"",
    "37": "Nightmare Sign \"Shadow Stealer to Wander Forever\"",
    "38": "Illusion Sign \"Wild Danmaku Arcanum\"",
    "42": "Nightmare Sign \"Fantasy Cursed Seal -Concentrate-\"",
    "44": "Nightmare Sign \"Fantasy Reversed Cursed Seal -Marred-\"",
    "45": "Nightmare Sign \"Fantasy Duplex Cursed Seal -Marred-\"",
    "46": "Nightmare Sign \"Good-Sealing Mines\"",
    "48": "Nightmare Sign \"Good-Sealing Mines V2\"",
    "50": "Nightmare Sign \"Fantasy Cursed Seal -Spread-\"",
    "52": "Nightmare Sign \"Fantasy Cursed Seal -Worn-\"",
    "54": "\"Cursed Persuasion Needles\"",
    "58": "Great Dusk of Time \"Hell Eclipse\"",
    "60": "Great Dusk of Time \"Eclipse of Hell\"",
    "62": "Light Sign \"Event Horizon\"",
    "64": "Light Sign \"Event Horizon -Fast Forward-\"",
    "66": "Magic Sign \"Graze Fire Wall\"",
    "69": "Magic Sign \"Infernal Graze Fire Wall\"",
    "70": "Light Sign \"Magic Hour\"",
    "74": "\"Rotating Great Dusk of Time\"",
    "76": "\"Rotating Great Dusk of Doubt\"",
    "78": "\"First Pure Light\"",
    "82": "\"Ultima Arrows\"",
    "86": "\"Flames of Hatred\"",
    "88": "\"Flames of Confusion and Hatred\"",
    "90": "\"Trembling, Shivering Bane of Existence\"",
    "94": "\"Binding Chains\"",
    "98": "\"Pure Invisible Drones\"",
    "101": "\"Pure, Refining Invisible Drones\"",
    "102": "\"Desperation Move\"",
    "104": "\"Desperation Move\"",
    "106": "Butterfly Dream \"Nightmarish Butterfly\"",
    "107": "Nightmare Sign \"Shadow Stealer -Fast Version-\"",
    "108": "Crawling Nightmare \"Creeping Shadow\"",
    "109": "Darkness \"Dark Impulse Hand\"",
    "110": "Dark Earth \"Aimed Quake\"",
    "111": "Dark Magic \"Dark Reflected Volley\"",
    "112": "\"Constantly Racing Darkness\"",
    "113": "Darkness \"Dark Wave\"",
    "114": "Dark Earth \"Racing Shockwave\"",
    "115": "Dark Planets \"Darkest Impact\"",
    "116": "\"Dark Soul\"",
    "117": "\"Dark Shadow\"",
    "118": "Dual Limit \"Double Ars Solum -Danmaku Version-\""
}
