{
    "0": "\"Evil Undulation\"",
    "2": "Illusion Bullet \"Cross Shooting\"",
    "5": "Mirage Bullet \"Cross Shoot Down\"",
    "6": "Illusionary Wave \"Lunatic Wave\"",
    "9": "Mirage Wave \"Lunatic Mind Blow\"",
    "10": "Glitch Sign \"Spreading Glitch\"",
    "12": "Glitch Sign \"Spreading Double Glitch\"",
    "14": "Glitch Sign \"Glitch Reflect\"",
    "16": "Glitch Sign \"Glitch Reflera\"",
    "17": "Glitch Sign \"Glitch Reflega\"",
    "18": "Glitch Sign \"Chaotic Glitch\"",
    "21": "Glitch Sign \"Lunatic Glitch\"",
    "22": "Nightmare Sign \"Scissor Bite\"",
    "24": "Nightmare Sign \"Binding Scissor Bite\"",
    "26": "Nightmare Sign \"Poison Arrow\"",
    "28": "Nightmare Sign \"Poison Arrows Combo\"",
    "29": "Nightmare Sign \"Neverending Poison Arrows Combo\"",
    "30": "Nightmare Sign \"Dark Wandering\"",
    "32": "Nightmare Sign \"Darkest Wandering\"",
    "34": "Nightmare Sign \"Shadow Stealer\"",
    "36": "Nightmare Sign \"Reversal Shadow Stealer\"",
    "37": "Nightmare Sign \"Shadow Stealer to Wander Forever\"",
    "38": "Illusion Sign \"Dark Arcanum\"",
    "42": "Nightmare Sign \"Dark Seal -Concentrate-\"",
    "44": "Nightmare Sign \"Dark Reversed Seal -Marred-\"",
    "45": "Nightmare Sign \"Dark Duplex Seal -Marred-\"",
    "46": "Nightmare Sign \"Light-Hiding Seal\"",
    "48": "Nightmare Sign \"Light-Hiding Seal V2\"",
    "50": "Nightmare Sign \"Dark Seal -Spread-\"",
    "52": "Nightmare Sign \"Dark Seal -Worn-\"",
    "54": "\"Dark Needles\"",
    "58": "\"Hidden Sunset\"",
    "60": "\"Hidden Twilight\"",
    "62": "Side Sign \"Halo of the Secret Nobody\"",
    "64": "Side Sign \"Halo of the Absolute Secret Nobody\"",
    "66": "Magic Sign \"Crawling Fire Wall\"",
    "69": "Magic Sign \"Infernal Crawling Fire Wall\"",
    "70": "\"Ultimate and Absolute Light Barrage\"",
    "74": "\"Hidden Nightfall\"",
    "76": "\"Hidden Dead of Night\"",
    "78": "\"First Pure Light\"",
    "82": "\"Ultima Arrows\"",
    "86": "\"Flames of Hatred\"",
    "88": "\"Flames of Hatred and Confusion\"",
    "90": "\"Continuous Earthquake\"",
    "94": "\"Binding Chains\"",
    "98": "\"Pure Invisible Drones\"",
    "101": "\"Purest Invisible Drones\"",
    "102": "\"Desperation Move\"",
    "104": "\"Desperation Move\"",
    "106": "Nightmare Sign \"Nightmarish Butterfly\"",
    "107": "Nightmare Sign \"Quick Shadow\"",
    "108": "Crawling Nightmare \"Creeping Shadow\"",
    "109": "Darkness \"Dark Impulse Hand\"",
    "110": "Dark Earth \"Aimed Quake\"",
    "111": "Dark Magic \"Dark Reflected Volley\"",
    "112": "\"Constantly Racing Darkness\"",
    "113": "Darkness \"Dark Wave\"",
    "114": "Dark Earth \"Racing Shockwave\"",
    "115": "Dark Planets \"Darkest Impact\"",
    "116": "\"Dark Soul\"",
    "117": "\"Dark Three Shadows\"",
    "118": "Dual Limit \"Double Danmaku Ars Solum\""
}
