{
    "70": "Light in the Back \"Dazzling Gleam of a Secret Human\"",
    "73": "Light in the Back \"Dazzling Gleam of an Absolute Secret Human\"",
    "74": "Hidden Summer \"Searing Summer Sun\"",
    "76": "Hidden Summer \"Abnormal Searing Inferno of the Harsh Sun\"",
    "78": "Hidden Fall \"Hunger Burst\"",
    "80": "Hidden Fall \"Abnormal Withering, Starving Burst\"",
    "82": "Hidden Winter \"Inharmonious Black Snowman\"",
    "84": "Hidden Winter \"Snowman of Abnormal Snow Burst\"",
    "86": "Hidden Spring \"Endless Evening Spring Gust\"",
    "88": "Hidden Spring \"Endless Evening Abnormal Spring Hurricane\"",
    "90": "Hidden Foe \"Hidden Breezy Cherry Blossom\"",
    "94": "Hidden Foe \"Hidden Perfect Summer Ice\"",
    "98": "Hidden Foe \"Hidden Crazy Fall Wind\"",
    "102": "Hidden Foe \"Hidden Extreme Winter\"",
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Backup Dance\"",
    "108": "Bullet Dance \"Twin Typhoons\"",
    "109": "Secret Chaos \"Behind the Scene's Dark Maze\"",
    "110": "Secret Chaos \"Disobedient Back Attackers\"",
    "111": "Secret Chaos \"Crawling Dupion Burst\"",
    "112": "Secret Chaos \"Back Firaga Burst\"",
    "113": "Secret Chaos \"Clumsy Yet Effective Bullet Reversal\"",
    "114": "Secret Chaos \"Blizzard Maze\"",
    "115": "Secret Chaos \"Shining Seven Stars\"",
    "116": "Secret Chaos \"Performers who Never Were\"",
    "117": "\"Impaled by the Secret Human\"",
    "118": "\"The Secret Human who Never Was\""
}