{
    "70": "Light in the Back \"Hidden Stars of a Secret Human\"",
    "73": "Light in the Back \"Hidden Stars of an Absolutely Secret Human\"",
    "74": "Hidden Summer \"Taste the Sunlight\"",
    "76": "Hidden Summer \"Zenith Sunshine of Abnormal Agressivity\"",
    "78": "Hidden Fall \"Windy Fall Leaves Crop\"",
    "80": "Hidden Fall \"Hurricane on the Fall Leaves Crop\"",
    "82": "Hidden Winter \"Dark Snow Cloak\"",
    "84": "Hidden Winter \"Nightmarish Abnormal Snow Ball Blizzard\"",
    "86": "Hidden Spring \"Evening Spring Blossom Shower\"",
    "88": "Hidden Spring \"Endless Evening Abnormal Blossom Butterflies\"",
    "90": "Hidden You \"Hidden Breezy Cherry Blossom\"",
    "94": "Hidden You \"Hidden Perfect Summer Ice\"",
    "98": "Hidden You \"Hidden Crazy Fall Wind\"",
    "102": "Hidden You \"Hidden Extreme Winter\"",
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Backup Dance\"",
    "108": "Bullet Dance \"Twin Typhoons\"",
    "109": "Secret Love \"Light Stars in Darkness\"",
    "110": "Secret Earth \"Rock Burst from the Earth's Power\"",
    "111": "Native Secrecy \"Double Snake and the Crawling Frogs\"",
    "112": "Reversed Secret \"Reversal Bow of Back & Forth\"",
    "113": "Lunatic Secret \"Gun of the Original Rabbit\"",
    "114": "Secret Dream \"Seal Barrage of Non Existence\"",
    "115": "Secret Stars \"Shining Seven Sapphires\"",
    "116": "Secret Enemies \"Reckless Stars VS. Lunar Danmaku\"",
    "117": "\"Mirage Split Back Sword\"",
    "118": "\"The Secret Human who Never Was\"",
    "121": "\"Hidden Wet and Dry Seasons\""
}