{
    "70": "Light in the Back \"Dazzling Gleam of a Secret Human\"",
    "73": "Light in the Back \"Dazzling Gleam of an Absolute Secret Human\"",
    "74": "Hidden Summer \"Inferno of the Summer Sun\"",
    "76": "Hidden Summer \"Abnormal Inferno of the Harsh Sun\"",
    "78": "Hidden Fall \"Withering Vitality\"",
    "80": "Hidden Fall \"Abnormal Withering Burst\"",
    "82": "Hidden Winter \"Black Snowman\"",
    "84": "Hidden Winter \"Snowman of Abnormal Snowfall\"",
    "86": "Hidden Spring \"Endless Evening Spring Wind\"",
    "88": "Hidden Spring \"Abnormal Hurricane of the Endless Spring Evening\"",
    "90": "Hidden Opponent \"Hidden Breezy Cherry Blossom\"",
    "94": "Hidden Opponent \"Hidden Perfect Summer Ice\"",
    "98": "Hidden Opponent \"Hidden Crazy Fall Wind\"",
    "102": "Hidden Opponent \"Hidden Extreme Winter\"",
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Backup Dance\"",
    "108": "Bullet Dance \"Twin Typhoons\"",
    "109": "Secret Chaos \"Behind the Scenes's Darkness\"",
    "110": "Secret Chaos \"Disobedient Back Attackers\"",
    "111": "Secret Chaos \"Creeping Dupion Burst\"",
    "112": "Secret Chaos \"Back Firaga Burst\"",
    "113": "Secret Chaos \"Clumsy Yet Effective Bullet Return\"",
    "114": "Secret Chaos \"Double Edge Needles\"",
    "115": "Secret Chaos \"Shining Seven Stars\"",
    "116": "Secret Chaos \"Performers who Never Were\"",
    "117": "\"Impaled by the Secret Human\"",
    "118": "\"The Secret Human who Never Was\""
}