{
    "51": "Secret Darkness \"Nightmare of the Dark Drown\"",
    "52": "Surprise Secret \"Sudden Drop to the Uprising Arrows\"",
    "53": "Light in the Back \"Nightmarish Stars of an Absolutely Secret Human\"",
    "54": "Secret Illusion \"Hidden Bullets of the Dream Rabbit\"",
    "55": "Secret Lock \"Pseudo-Time Rewind Bind\"",
    "57": "Scarlet Devil Sign \"Bloody Catastrophe\"",
    "61": "Divine Scarlet Sign \"Bloody Laser of Seventeen Articles\"",
    "62": "Scarlet Star Sign \"Superhuman Catastrophe Pilgrimage\"",
    "64": "Wind God Sign \"Mishabashira\"",
    "66": "Wind Flower Sign \"Mishaguji-sama's Right and Wrong\"",
    "68": "Wind Flower Sign \"Onbashira Trial\"",
    "72": "Shining Night Sign \"Big Bullet Branch of Hourai\"",
    "70": "Scarlet Needle Sign \"Keystones Grow Bigger, Too!\"",
    "69": "Eternal Night Sign \"Bullet Branch of Hourai in a Pot\"",
    "74": "Scarlet Night Sign \"Bullet Keystones of Hourai\"",
    "75": "Earth Spirit Sign \"Mind Stellar Steal\"",
    "76": "Earth Mystic Sign \"Shikigami of the Id\"",
    "77": "\"Perfect Mind Control\"",
    "78": "Earth Mystic Sign \"Shikigami's Giant Star\"",
    "80": "Earth Spirit Sign \"Mind Stellar Relief\"",
    "81": "Divine Star Sign \"Unidentified Ghost-Light Crowd\"",
    "82": "Shining Heaven Sign \"Thunderclap Dondoko Drum\"",
    "83": "Shining Divine Sign \"Mysterious Dondoko Crowd\"",
    "84": "Scarlet Star Sign \"Unidentified Lightning Strike\"",
    "85": "Divine Scarlet Sign \"Stalker in a Thunderstorm\"",
    "86": "Shining Star Sign \"Unidentified Dondoko Drum\"",
    "87": "Gathering Night Sign \"Precious Life Scatters like Mist\"",
    "88": "Ultramarine Orb Sign \"Pure and Impure Danmaku\"",
    "91": "Gathering Orb Sign \"Mist Ray\"",
    "92": "Eternal Orb Sign \"An Unsullied Orb and a Much-Sullied Spirit\"",
    "93": "\"Lunatic Secret Barrier\"",
    "96": "\"Shoot the Danmaku Barrier!\"",
    "94": "\"Sneak-Photographer Exorcism Master Spark\"",
    "99": "\"The Nightmare One Has on Their Final Sunday\"",
    "100": "Paper Sign \"Zener Card Shuriken\"",
    "101": "Paper Sign \"Barrier-Enclosed Zener Card Shuriken\"",
    "58": "Star Divine Sign \"Superhuman of Seventeen Articles\"",
    "59": "Scarlet Star Sign \"Superhuman's Bloody Knife\"",
    "60": "Scarlet Divine Sign \"Catastrophe of Seventeen Articles\"",
    "63": "Mystic Flower Sign \"Butterfly Storm Yama Scepter\"",
    "65": "Wind Mystic Sign \"Dead Butterfly Onbashira\"",
    "67": "Mystic Wind Sign \"Native Butterfly Storm\"",
    "71": "Eternal Scarlet Sign \"Plummeting Bhava-agra in a Pot\"",
    "73": "Eternal Shining Sign \"Pot Growing Bigger\"",
    "79": "Earth Mystic Sign \"Shikigami of the Ego\"",
    "89": "Gathering Orb Sign \"Purely Beyond All in the Fog\"",
    "90": "Eternal Orb Sign \"Reckless Sacrifice's Reflection\"",
    "95": "Union \"Sneak-Photographer Exorcism from the Back\"",
    "97": "Union \"Coward's Master Spark\"",
    "98": "\"Unauthorized Danmaku Photography is Strictly Prohibited\""
}