{
    "0": "Horror \"Cave Mushroom Apparition\"",
    "2": "Yamame Kurodani \"Capture Web\"",
    "4": "Yamame Kurodani \"Cave Spider's Nest\"",
    "6": "Yamame Kurodani \"Filled Miasma\"",
    "8": "OH BOI \"Hidden Mickey\"",
    "10": "Nightmare \"Green Shadow\"",
    "12": "Nightmare \"Green Invisible Shadow\"",
    "14": "Poison \"Poison Flowers\"",
    "16": "Poison \"Poison Flowers\"",
    "18": "Cloning \"Dream and Nightmare\"",
    "20": "Cloning \"Dream and Fearsome Nightmare\"",
    "22": "Malice Sign \"Nightmarish Abyss\"",
    "24": "Malice Sign \"Seventh Nightmarish Abyss\"",
    "26": "Power Sign \"Quake Scramble\"",
    "30": "Quake \"Lingering Quakes\"",
    "32": "Bind \"Lingering Binding Quakes\"",
    "34": "Rock Shatter \"Rock Storm\"",
    "36": "Rock Shatter \"Rocks Blowing Down from Darkness\"",
    "38": "Final Limit \"Three Steps Ground Impact\"",
    "40": "Final Limit \"Three Steps Ground Impact\"",
    "42": "Remembrance \"Remembrance Snatch\"",
    "44": "Remembrance \"Cyclone Remembrance Snatch\"",
    "46": "Remembrance \"Double Black Death Butterfly\"",
    "50": "Remembrance \"Flying Insect's Nest\"",
    "54": "Remembrance \"Border of Wave & Particle\"",
    "58": "Remembrance \"Throwing Mt. Togakushi\"",
    "62": "Remembrance \"Pandemonium\"",
    "66": "Remembrance \"Deep Mist Labyrinth\"",
    "70": "Remembrance \"Wind God Hidden Among Tree Leaves\"",
    "74": "Remembrance \"Tengu's Macroburst\"",
    "78": "Remembrance \"Torii Whorl-Wind\"",
    "82": "Remembrance \"Spring Kyoto Dolls\"",
    "86": "Remembrance \"Straw Doll Kamikaze\"",
    "90": "Remembrance \"Return Inanimateness\"",
    "94": "Remembrance \"Mercury Poison\"",
    "98": "Remembrance \"Princess Undine\"",
    "102": "Remembrance \"Philosopher's Stone\"",
    "106": "Remembrance \"Extending Arm\"",
    "110": "Remembrance \"Kappa's Pororoca\"",
    "114": "Remembrance \"Trauma in the Glimmering Depths\"",
    "118": "Heartless \"Dark Walk\"",
    "120": "Heartless \"Heartless Spirit's Erratic Step\"",
    "122": "Darkness \"Lurking Shadows\"",
    "124": "Darkness \"Vengeful Spirit: Possessed Shadows\"",
    "126": "Darkness \"Dark Claws\"",
    "128": "Darkness \"Vengeful Dark Claws\"",
    "130": "Darkness \"Dark Blizzara\"",
    "132": "Darkness \"Dark Blizzaga\"",
    "134": "\"Dark Revenge\"",
    "136": "\"Dark Revenge\"",
    "138": "Darkness \"Dark Firaga Wheel\"",
    "142": "Atomic Fire \"Nuclear Fire\"",
    "144": "Atomic Fire \"Fira Excursion\"",
    "145": "Atomic Fire \"Uncontainable Firaga Explosion\"",
    "146": "Explosion Sign \"Petit Flare\"",
    "147": "Explosion Sign \"Mega Flare\"",
    "148": "Explosion Sign \"Giga Flare\"",
    "149": "Explosion Sign \"Peta Flare\"",
    "150": "Blazing Hidden Star \"Fixed Star\"",
    "152": "Blazing Hidden Star \"Planetary Revolution\"",
    "153": "Blazing Hidden Star \"Ten Evil Stars\"",
    "154": "\"Duel of the Two Suns\"",
    "156": "\"Hell's Sun Clash\"",
    "158": "Final Limit \"Hidden Sun\"",
    "160": "Final Limit \"Hidden Subterranean Sun\"",
    "162": "Esoterica \"Nine Syllable Stabs\"",
    "163": "Miracle \"Miracle Fruit\"",
    "164": "Divine Virtue \"Bumper Crop Rice Shower\"",
    "165": "Darkness \"Helm Split Columns\"",
    "166": "Magic \"Bind\"",
    "167": "Front Sign \"Revealed Light Star\"",
    "168": "Back Sign \"Hidden Dark Star\"",
    "169": "Dark Stopga \"Dark Splicer\"",
    "170": "Dark Subconscious \"Frozen Maelstrom\"",
    "171": "Crawling Dark Firaga \"The Embers of Love\"",
    "172": "Deep Darkness \"Dark Aura\"",
    "173": "\"Hidden Shadow in Dark Auras\"",
    "174": "Final Limit \"Hidden Subterranean Darkness\""
}
