{
    "0": "Horror \"Cave Mushroom Apparition\"",
    "2": "Magic \"Capture Bind\"",
    "4": "Magic \"Collision Magnet\"",
    "6": "Shards \"Icebreaker\"",
    "8": "Light Shards \"Hidden Mickey\"",
    "10": "Nightmare \"Green Shadow\"",
    "12": "Nightmare \"Green Invisible Shadow\"",
    "14": "Poison \"Poison Flowers\"",
    "16": "Poison \"Poison Flowers\"",
    "18": "Shadow Double \"Dream and Nightmare\"",
    "20": "Shadow Double \"Sweet Dream and Dreadful Nightmare\"",
    "22": "Nightmare \"Nightmarish Abyss\"",
    "24": "Nightmare \"Absolutely Nightmarish Abyss\"",
    "26": "Power Sign \"Quake Scramble\"",
    "30": "Quake \"Lingering Quakes\"",
    "32": "Bind \"Lingering Binding Quakes\"",
    "34": "Rock Shatter \"Rock Storm\"",
    "36": "Rock Shatter \"Rocks Blowing Down from Darkness\"",
    "38": "Final Limit \"Three Steps Ground Impact\"",
    "40": "Final Limit \"Three Steps Ground Impact\"",
    "42": "Remembrance \"Remembrance Snatch\"",
    "44": "Remembrance \"Cyclone Remembrance Snatch\"",
    "46": "Remembrance \"Double Black Death Butterfly\"",
    "50": "Remembrance \"Flying Insect's Nest\"",
    "54": "Remembrance \"Border of Wave & Particle\"",
    "58": "Remembrance \"Throwing Mt. Togakushi\"",
    "62": "Remembrance \"Pandemonium\"",
    "66": "Remembrance \"Deep Mist Labyrinth\"",
    "70": "Remembrance \"Wind God Hidden Among Tree Leaves\"",
    "74": "Remembrance \"Tengu's Macroburst\"",
    "78": "Remembrance \"Torii Whorl-Wind\"",
    "82": "Remembrance \"Spring Kyoto Dolls\"",
    "86": "Remembrance \"Straw Doll Kamikaze\"",
    "90": "Remembrance \"Return Inanimateness\"",
    "94": "Remembrance \"Mercury Poison\"",
    "98": "Remembrance \"Princess Undine\"",
    "102": "Remembrance \"Philosopher's Stone\"",
    "106": "Remembrance \"Extending Arm\"",
    "110": "Remembrance \"Kappa's Pororoca\"",
    "114": "Remembrance \"Trauma in the Glimmering Depths\"",
    "118": "Heartless \"Dark Slide\"",
    "120": "Heartless \"Dark Rush\"",
    "122": "Darkness \"Demon Tower\"",
    "124": "Darkness \"Demon Huge Tower\"",
    "126": "Darkness \"Dark Claws\"",
    "128": "Darkness \"Vengeful Dark Claws\"",
    "130": "Darkness \"Dark Blizzara\"",
    "132": "Darkness \"Dark Blizzaga\"",
    "134": "\"Demon Tide\"",
    "136": "\"Ultimate Demon Tide\"",
    "138": "Darkness \"Dark Firaga Wheel\"",
    "142": "Atomic Fire \"Nuclear Fire\"",
    "144": "Atomic Fire \"Fira Excursion\"",
    "145": "Atomic Fire \"Uncontainable Firaga Explosion\"",
    "146": "Hidden Explosion \"Petit Flare\"",
    "147": "Hidden Explosion \"Mega Flare\"",
    "148": "Hidden Explosion \"Giga Flare\"",
    "149": "Hidden Explosion \"Peta Flare\"",
    "150": "Blazing Hidden Star \"Fixed Hidden Star\"",
    "152": "Blazing Hidden Star \"Hidden Planetary Revolution\"",
    "153": "Blazing Hidden Star \"Ten Dark Stars\"",
    "154": "\"Front Star and Back Star\"",
    "156": "\"Hidden Star and Revealed Star\"",
    "158": "Expulsion \"Hidden Sun\"",
    "160": "Expulsion \"Hidden Dark Sun\"",
    "162": "Esoterica \"Nine Syllable Stabs\"",
    "163": "Miracle \"Miracle Fruit\"",
    "164": "Divine Virtue \"Bumper Crop Rice Shower\"",
    "165": "Darkness \"Helm Split Columns\"",
    "166": "Magic \"Bind\"",
    "167": "Front Sign \"Revealed Light Star\"",
    "168": "Back Sign \"Hidden Dark Star\"",
    "169": "Dark Stopga \"Dark Splicer\"",
    "170": "Dark Subconscious \"Frozen Maelstrom\"",
    "171": "Crawling Dark Firaga \"The Embers of Love\"",
    "172": "Deep Darkness \"Dark Aura\"",
    "173": "\"Hidden Shadow in Three Auras\"",
    "174": "\"Hidden Dark Outflow\""
}
