{
    "0": "Bug Sign \"Scale Blizzard\"",
    "2": "Bug Sign \"Swallowtail Scale Blizzard\"",
    "4": "Bug Freeze \"Fluttering Summer\"",
    "6": "Bug Freeze \"Midsummer Wingbeats\"",
    "8": "Rain Sign \"Feather Rain\"",
    "10": "Rain Sign \"Torrential Feather Rain\"",
    "12": "Wind \"Fast Current\"",
    "14": "Wind \"Torrential Fast Current\"",
    "16": "Tornado \"Blade Gust\"",
    "18": "Tornado \"Bloody Gust\"",
    "20": "Lily White \"Surprise Spring\"",
    "22": "Reality Sign \"Non-Fantasy Seal -Concentrate-\"",
    "24": "Reality Sign \"Non-Fantasy Seal -Marred-\"",
    "26": "\"Persuasion Curvy Needles\"",
    "29": "\"Nine Persuasion Curvy Needles\"",
    "30": "Illusionary Double \"Double Cherry Blossom Seal\"",
    "34": "Orb Sign \"Orb Spot\"",
    "36": "Orb Sign \"Orb Spot\"",
    "38": "Magic Bullet \"Test Slave\"",
    "42": "Filop \"Flames Reaching the Moon\"",
    "46": "Darkness \"Tojiko within Lasers\"",
    "48": "Darkness \"Dark Green Thundaga\"",
    "50": "Darkness \"Curved Release\"",
    "54": "Darkness \"Chaos Stars\"",
    "62": "Darkness \"Buttfest\"",
    "58": "Darkness \"Behind You\"",
    "66": "Darkness \"Double Lasers\"",
    "118": "Okina Matara \"Anarchy Bullet Hell\"",
    "109": "Filop \"Reverse Ideo... I mean Invoker\"",
    "115": "Light \"Inverse Burst\"",
    "106": "Darkness \"Move in Your Safespot\"",
    "107": "Darkness \"Crazy Back Dance\"",
    "108": "Darkness \"Actual Nameless Danmaku\"",
    "74": "Summer Memories \"Heat Wave From All Sides\"",
    "78": "Fall Memories \"Die of Famine\"",
    "82": "Winter Memories \"Halo of the Guse Kannon out of Common Sense\"",
    "86": "Spring Memories \"Fancy April Wizard\"",
    "87": "Spring Memories \"Fancy April Wizard\"",
    "90": "Okina Matara \"Hidden Breezy Cherry Blossom\"",
    "93": "\"Die in a Cherry Blossom Chaotic Nightmare\"",
    "94": "Okina Matara \"Hidden Perfect Summer Ice\"",
    "97": "\"Die in a Nevermelting Summer Blizzard\"",
    "98": "Okina Matara \"Hidden Crazy Fall Wind\"",
    "101": "\"Die in a Fall Hurricane\"",
    "102": "Okina Matara \"Hidden Extreme Winter\"",
    "104": "\"Die in a Pure Winter Blizzard\"",
    "113": "Git Gud \"Spin Around and Get Stuck\"",
    "114": "Messy \"Spiral Return\"",
    "116": "Filop \"Falling Enemies\"",
    "111": "Tight Dodge \"Dupion Danmaku\"",
    "37": "Orb Sign \"Tight Orb Spot\"",
    "44": "Filop \"Flames Reaching the Moon at Winter\"",
    "117": "Secretly Released Timeout \"The Back Face's Dark Sarugaku\"",
    "70": "Illusionary Memories \"Memory of the Bright Hidden Stars\"",
    "73": "Illusionary Memories \"Memory of the Overly Bright Hidden Stars\"",
    "84": "Winter Memories \"Guse Flash out of Common Sense\"",
    "76": "Summer Memories \"Scorched Earth From All Sides\"",
    "80": "Fall Memories \"Starving Preta of Abnormal Blight\"",
    "88": "Spring Memories \"Mirage Sorcerer of Abnormal Falling Flowers\"",
    "89": "Spring Memories \"Mirage Sorcerer of Abnormal Falling Flowers\"",
    "40": "Magic Bullet \"Gigantic Test Slave\"",
    "68": "Darkness \"Try Hard Double Lasers\"",
    "110": "Filop \"Shot in the Back\"",
    "112": "Reverse Secrecy \"Decree of the Dream Flames of Heaven & Earth\""
}
