{
    "0": "Bug Sign \"Scale Blizzard\"",
    "2": "Bug Sign \"Swallowtail Scale Blizzard\"",
    "4": "Bug Freeze \"Fluttering Summer\"",
    "6": "Bug Freeze \"Midsummer Wingbeats\"",
    "8": "Rain Sign \"Feather Dance\"",
    "10": "Rain Sign \"Feather Mad Dance\"",
    "12": "Wind \"Current Grind\"",
    "14": "Wind \"Storm Grind\"",
    "16": "Tornado \"Blade Gust\"",
    "18": "Tornado \"Bloody Gust\"",
    "20": "\"Pure Illusionary Spring\"",
    "22": "Reality Sign \"Non-Fantasy Seal -Concentrate-\"",
    "24": "Reality Sign \"Non-Fantasy Seal -Marred-\"",
    "26": "\"Persuasion Curvy Needles\"",
    "29": "\"Nine Persuasion Curvy Needles\"",
    "30": "Illusionary Double \"Double Cherry Blossom Seal\"",
    "34": "Orb Sign \"Orb Spot\"",
    "36": "Orb Sign \"Orb Spot\"",
    "38": "Magic Bullet \"Test Slave\"",
    "42": "Light Sign \"Flames Reaching the Moon\"",
    "46": "Darkness \"Tojiko within Lasers\"",
    "48": "Darkness \"Dark Green Thundaga\"",
    "50": "Light \"Purple Ragnarok\"",
    "54": "Darkness \"Chaos Stars\"",
    "62": "Light & Darkness \"Storm Reversal\"",
    "58": "Reverse Light \"Behind Reversal\"",
    "66": "Light & Darkness \"Double Lasers\"",
    "118": "Okina Matara \"Anarchy Bullet Hell\"",
    "109": "Reverse Secrecy \"Reverse Darkness\"",
    "115": "Darkness \"Inverse Halo\"",
    "106": "Light & Darkness \"Falling Back Storm\"",
    "107": "Light & Darkness \"Rising Back Storm\"",
    "108": "Light & Darkness \"Union of the Two Halves\"",
    "74": "Summer Memories \"Scorch from the Bright Star\"",
    "78": "Fall Memories \"Reverse Miracle\"",
    "82": "Winter Memories \"Solo Dark Blizzard Limit\"",
    "86": "Spring Memories \"Reverse Cherry Blossom Attack\"",
    "87": "Spring Memories \"Reverse Cherry Blossom Attack\"",
    "90": "Okina Matara \"Hidden Breezy Cherry Blossom\"",
    "94": "Okina Matara \"Hidden Perfect Summer Ice\"",
    "98": "Okina Matara \"Hidden Crazy Fall Wind\"",
    "102": "Okina Matara \"Hidden Extreme Winter\"",
    "113": "Reversal \"Spiral Return\"",
    "114": "Reversal \"Reverse Spiral Attack\"",
    "116": "Reversal \"Falling Enemies\"",
    "111": "Bind \"Danmaku Catcher\"",
    "37": "Orb Sign \"Tight Orb Spot\"",
    "44": "Light Blast \"Flames Reaching the Moon at Winter\"",
    "117": "\"The Phantom Secretly Existing on Your Back\"",
    "70": "Miracle Memories \"Memory of the Bright Hidden Stars\"",
    "73": "Miracle Memories \"Memory of the Overly Bright Hidden Stars\"",
    "84": "Winter Memories \"Solo Dark Blizzara Limit\"",
    "85": "Winter Memories \"Solo Dark Blizzaga Limit\"",
    "76": "Summer Memories \"Scorching Drought from the Bright Star\"",
    "80": "Fall Memories \"Change Air Miracle\"",
    "88": "Spring Memories \"Reverse Abnormal Cherry Blossom Attack\"",
    "89": "Spring Memories \"Reverse Abnormal Cherry Blossom Attack\"",
    "40": "Magic Bullet \"Gigantic Test Slave\"",
    "68": "Light & Darkness \"Try Hard Double Lasers\"",
    "110": "Deceit Secrecy \"Shot in the Back\"",
    "112": "Reverse Secrecy \"Overturning All Behind You\""
}
