{
    "68": "\"All My Bullets are Belong to You\"",
    "70": "\"All My Bullets are Belong to You\"",
    "71": "\"All My Danmaku are Belong to You\"",
    "76": "\"Rainbow-Shaped Sculpting Art\"",
    "78": "\"Rainbow-Shaped Sculpting Art\"",
    "79": "\"Rainbow-Shaped Sculpting Art\"",
    "80": "\"Asylum of Sanic Danmaku\"",
    "60": "\"An Unquestionable Offering to the Ownerless\"",
    "62": "\"An Offering to the Blinking Rainbow Fantasy Seal\"",
    "64": "\"Readability Hoarder's Obsession\"",
    "72": "\"Rainbow Ring of Drunk People\"",
   "44": "Calamitous Star \"Dance of Star-Sparked Backfire\"",
    "46": "Calamitous Star \"Wild Dance of Star-Sparked Backfire\"",
    "48": "Stellar Wind \"Dance of Everlasting Iridescence\"",
    "50": "Stellar Wind \"Wild Dance of Everlasting Iridescence\"",
    "56": "Rainbow Illumination \"Clear Yet Startling Wind and Moon\"",
    "52": "Luminous Horse \"Homing Dash of Sky-Racing Heavenly Steeds\"",
    "54": "Luminous Horse \"Wild Homing Dash of Sky-Racing Heavenly Steeds\"",
    "92": "I Forbid It \"No More Fun!\"",
    "91": "Fireworks \"Fireworks from Every Wall\"",
    "90": "Parody \"I Reversed Gravity on This Mine Dump!\"",
    "87": "Parody \"Mine Are Longer!\"",
    "88": "Illusion Sign \"Creeping Close Illusionary Clones\"",
    "89": "Thunder Sign \"Vertical Electric Fence Maze\"",
    "93": "Thunder Sign \"Sniping Thunder Spears From Far Away\"",
    "94": "Upgraded Ability Card \"Gluttonous Five Centipedes\"",
    "95": "\"Haha Orbs Go Nom-Nom\"",
    "96": "\"Final Spell Card Hype!\"",
}