{
    "0": "Piercing Chill \"Frost Columns\"",
    "1": "Piercing Chill \"Frost Columns -Lunatic-\"",
    "2": "Piercing Chill \"Lingering Cold -Easy-\"",
    "3": "Piercing Chill \"Lingering Cold\"",
    "4": "Piercing Chill \"Lingering Cold -Hard-\"",
    "5": "Piercing Chill \"Lingering Cold -Lunatic-\"",
    "6": "Piercing Chill \"Flower Wither Away -Easy-\"",
    "7": "Piercing Chill \"Flower Wither Away\"",
    "8": "Piercing Chill \"Undulation Ray\"",
    "9": "Piercing Chill \"Table-Turning\"",
    "10": "Nightmare \"Dream Eater Egg -Easy-\"",
    "11": "Nightmare \"Dream Eater\"",
    "12": "Nightmare \"Dream Eater Spread Wings\"",
    "13": "Nightmare \"Dream Eater Spread Wings -Lunatic-\"",
    "14": "Nightmare \"Pentagram Flight -Easy-\"",
    "15": "Nightmare \"Pentagram Flight\"",
    "16": "Nightmare \"Douman-Seiman\"",
    "17": "Nightmare \"Large Pentagram Crest\"",
    "18": "Nightmare \"Immortal Dream Eater's Rumbling -Easy-\"",
    "19": "Nightmare \"Immortal Dream Eater's Rumbling\"",
    "20": "Nightmare \"Flight of Idaten\"",
    "21": "Nightmare \"Dharmapala's Rampage\"",
    "22": "Nightmare \"Incarnate Immortal Dream Eater -Easy-\"",
    "23": "Nightmare \"Incarnate Immortal Dream Eater\"",
    "24": "Nightmare \"Konjin of the Demon's Gate\"",
    "25": "Nightmare \"Kimontonkou\"",
    "26": "Remembrance \"Maiden's Bunraku\"",
    "27": "Remembrance \"Maiden's Bunraku -Lunatic-\"",
    "28": "Remembrance \"Benevolent French Dolls -Easy-\"",
    "29": "Remembrance \"Benevolent French Dolls\"",
    "30": "Remembrance \"Benevolent French Dolls -Hard-\"",
    "31": "Remembrance \"Benevolent Orléans Dolls\"",
    "32": "Remembrance \"Red-Haired Dutch Dolls -Easy-\"",
    "33": "Remembrance \"Red-Haired Dutch Dolls\"",
    "34": "Remembrance \"Chalk-White Russian Dolls\"",
    "35": "Remembrance \"Chalk-White Russian Dolls -Lunatic-\"",
    "36": "Remembrance \"Foggy London Dolls -Easy-\"",
    "37": "Remembrance \"Foggy London Dolls\"",
    "38": "Remembrance \"Reincarnating Tibetan Dolls\"",
    "39": "Remembrance \"Spring Kyoto Dolls\"",
    "40": "Remembrance \"Eerily Luminous Shanghai Dolls -Easy-\"",
    "41": "Remembrance \"Eerily Luminous Shanghai Dolls\"",
    "42": "Remembrance \"Eerily Luminous Shanghai Dolls -Hard-\"",
    "43": "Remembrance \"Hanged Hourai Dolls\"",
    "44": "Snatch \"Phantom Dinning -Easy-\"",
    "45": "Snatch \"Phantom Dinning\"",
    "46": "Snatch \"Live Poltergeist\"",
    "47": "Snatch \"Live Poltergeist -Lunatic-\"",
    "48": "Snatch \"Guarneri del Gesù -Easy-\"",
    "49": "Snatch \"Guarneri del Gesù\"",
    "50": "Snatch \"Stradivarius\"",
    "51": "Snatch \"Pseudo Stradivarius\"",
    "52": "Snatch \"Hino Phantasm -Easy-\"",
    "53": "Snatch \"Hino Phantasm\"",
    "54": "Snatch \"Ghost Clifford\"",
    "55": "Snatch \"Ghost Clifford -Lunatic-\"",
    "56": "Snatch \"Fazioli Nether Performance -Easy-\"",
    "57": "Snatch \"Fazioli Nether Performance\"",
    "58": "Snatch \"Bösendorfer Divine Performance\"",
    "59": "Snatch \"Bösendorfer Divine Performance -Lunatic-\"",
    "60": "Snatch \"Prism Concerto -Easy-\"",
    "61": "Snatch \"Prism Concerto\"",
    "62": "Snatch \"Stygian Riverside\"",
    "63": "Snatch \"Stygian Riverside -Lunatic-\"",
    "64": "Corrupted \"Triple Catastrophe -Easy-\"",
    "65": "Corrupted \"Triple Catastrophe\"",
    "66": "Corrupted \"Triple Catastrophe: Revised\"",
    "67": "Corrupted \"Triple Catastrophe: Wonderous\"",
    "68": "Deathscythe \"Phantom Saber -Easy-\"",
    "69": "Deathscythe \"Phantom Saber\"",
    "70": "Deathscythe \"Crescent Saber\"",
    "71": "Deathscythe \"Retribution Saber\"",
    "72": "Deathscythe \"Flash Scythe -Easy-\"",
    "73": "Deathscythe \"Flash Scythe\"",
    "74": "Deathscythe \"Duplicate Slashes\"",
    "75": "Deathscythe \"Multiplicative Slashes\"",
    "76": "Deathscythe \"Racing Scythe -Easy-\"",
    "77": "Deathscythe \"Racing Scythe\"",
    "78": "Deathscythe \"Magnet Scythe\"",
    "79": "Deathscythe \"Magnet Scythe -Lunatic-\"",
    "80": "Deathscythe \"Back Slash -Easy-\"",
    "81": "Deathscythe \"Back Slash\"",
    "82": "Deathscythe \"Back Slash -Hard-\"",
    "83": "Deathscythe \"Back Slash -Lunatic-\"",
    "84": "Limit Break \"Bloom Out -Easy-\"",
    "85": "Limit Break \"Bloom Out\"",
    "86": "Limit Break \"Bloom Out -Hard-\"",
    "87": "Limit Break \"Bloom Out -Lunatic-\"",
    "88": "Final Limit \"Full Bloom -Easy-\"",
    "89": "Final Limit \"Full Bloom\"",
    "90": "Final Limit \"Full Bloom -Hard-\"",
    "91": "Final Limit \"Full Bloom -Lunatic-\"",
    "92": "Sleight \"Side Laser -Wandering Soul-\"",
    "93": "Sleight \"Side Laser -Past Sin-\"",
    "94": "Sleight \"Side Laser -Trackless Path-\"",
    "95": "Sleight \"Side Laser -Suicide-\"",
    "96": "Sleight \"Gale of Severance -Bewilderment-\"",
    "97": "Sleight \"Gale of Severance -Dead Butterfly-\"",
    "98": "Sleight \"Gale of Severance -Poisonous Moth-\"",
    "99": "Sleight \"Gale of Severance -Demon World-\"",
    "100": "Sleight \"Doom\"",
    "101": "Sleight \"Doom\"",
    "102": "Sleight \"Doom\"",
    "103": "Sleight \"Doom\"",
    "104": "Sleight \"Whirlwind to the Void -False Soul-\"",
    "105": "Sleight \"Whirlwind to the Void -Ghost-\"",
    "106": "Sleight \"Whirlwind to the Void -Phantom Spirit-\"",
    "107": "Sleight \"Whirlwind to the Void -Divine Spirit-\"",
    "108": "Cherry Blossom Sign \"Disappearance in Cherry Blossom -Seal-\"",
    "109": "Cherry Blossom Sign \"Disappearance in Cherry Blossom -Self-Loss-\"",
    "110": "Cherry Blossom Sign \"Disappearance in Cherry Blossom -Spring Sleep-\"",
    "111": "Cherry Blossom Sign \"Disappearance in Cherry Blossom -Bloom-\"",
    "112": "\"Absent Silhouette -10%% Reflowering-\"",
    "113": "\"Absent Silhouette -30%% Reflowering-\"",
    "114": "\"Absent Silhouette -50%% Reflowering-\"",
    "115": "\"Absent Silhouette -80%% Reflowering-\"",
    "116": "Nightmare \"Dream and Nightmare\"",
    "117": "Nightmare \"Flowmotion Rush\"",
    "118": "Unversed \"Unversed Thoughts\"",
    "119": "Unversed \"Clone Burst\"",
    "120": "Unversed \"Dark Fang -Radiance-\"",
    "121": "Unversed \"Dark Fang -Binding-\"",
    "122": "Unversed \"Shadow Dive\"",
    "123": "Unversed \"X-Charge\"",
    "124": "Unversed \"Dark Blizzaga\"",
    "125": "Nightmare \"Anti Black Coat Nightmare\"",
    "126": "\"Flowing Time\"",
    "127": "Limit Break \"Wild Danmaku Arcanum\"",
    "128": "Unversed \"Noname and Antinitas\"",
    "129": "Unversed \"Dark Spiral\"",
    "130": "Manipulation \"Spell/Curse of Dreams & Reality\"",
    "131": "Slow \"Zero Shot\"",
    "132": "Spear Orbs \"Mesh of Light and Darkness\"",
    "133": "Keyblade \"Flash Liner\"",
    "134": "Combo \"Teleport Flash Liner\"",
    "135": "Dream Butterfly \"X-Charge\"",
    "136": "Finish \"Double Black Death Butterfly\"",
    "137": "Unversed \"Antinitas Remnant\"",
    "138": "\"Restricting Clock\"",
    "139": "Limit Break \"Wild Danmaku Arcanum\"",
    "140": "Time Stop \"Danmaku Clock Barrier\""
}